package com.parneet.smartlayer.model

data class StreamVideo(
    val title: String?,
    val streamUrl: String?,
    val streamSubtitle: List<StreamSubtitle?>?
)

data class StreamSubtitle(
    val displayName: String,
    val subtitleStreamUrl: String,
    val isAutoGeneratedByYoutube: Boolean
)