package com.parneet.smartlayer.model

data class YoutubeStream(
    val title: String?,
    val videoOnlyStreams: List<StreamVideoOnly>,
    val streamSubtitle: List<StreamSubtitle?>?
)

data class StreamVideoOnly(
    val streamUrl: String,
    val resolution: String,
    val fps: Int,
    val codec: String
)

data class StreamSubtitle(
    val displayName: String,
    val subtitleStreamUrl: String,
    val isAutoGeneratedByYoutube: Boolean
)