// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/discuss_service.proto

package com.google.ai.generativelanguage.v1beta3;

public interface CountMessageTokensRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ai.generativelanguage.v1beta3.CountMessageTokensRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The model's resource name. This serves as an ID for the Model to
   * use.
   *
   * This name should match a model name returned by the `ListModels` method.
   *
   * Format: `models/{model}`
   * </pre>
   *
   * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <pre>
   * Required. The model's resource name. This serves as an ID for the Model to
   * use.
   *
   * This name should match a model name returned by the `ListModels` method.
   *
   * Format: `models/{model}`
   * </pre>
   *
   * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <pre>
   * Required. The prompt, whose token count is to be returned.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta3.MessagePrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the prompt field is set.
   */
  boolean hasPrompt();
  /**
   * <pre>
   * Required. The prompt, whose token count is to be returned.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta3.MessagePrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The prompt.
   */
  com.google.ai.generativelanguage.v1beta3.MessagePrompt getPrompt();
  /**
   * <pre>
   * Required. The prompt, whose token count is to be returned.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta3.MessagePrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.ai.generativelanguage.v1beta3.MessagePromptOrBuilder getPromptOrBuilder();
}
