// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/model_service.proto

package com.google.ai.generativelanguage.v1beta3;

/**
 * <pre>
 * Metadata about the state and progress of creating a tuned model returned from
 * the long-running operation
 * </pre>
 *
 * Protobuf type {@code google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata}
 */
public final class CreateTunedModelMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata)
    CreateTunedModelMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTunedModelMetadata.newBuilder() to construct.
  private CreateTunedModelMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTunedModelMetadata() {
    tunedModel_ = "";
    snapshots_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateTunedModelMetadata();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ai.generativelanguage.v1beta3.ModelServiceProto.internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ai.generativelanguage.v1beta3.ModelServiceProto.internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.class, com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.Builder.class);
  }

  public static final int TUNED_MODEL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tunedModel_ = "";
  /**
   * <pre>
   * Name of the tuned model associated with the tuning operation.
   * </pre>
   *
   * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
   * @return The tunedModel.
   */
  @java.lang.Override
  public java.lang.String getTunedModel() {
    java.lang.Object ref = tunedModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tunedModel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the tuned model associated with the tuning operation.
   * </pre>
   *
   * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
   * @return The bytes for tunedModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTunedModelBytes() {
    java.lang.Object ref = tunedModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tunedModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_STEPS_FIELD_NUMBER = 1;
  private int totalSteps_ = 0;
  /**
   * <pre>
   * The total number of tuning steps.
   * </pre>
   *
   * <code>int32 total_steps = 1;</code>
   * @return The totalSteps.
   */
  @java.lang.Override
  public int getTotalSteps() {
    return totalSteps_;
  }

  public static final int COMPLETED_STEPS_FIELD_NUMBER = 2;
  private int completedSteps_ = 0;
  /**
   * <pre>
   * The number of steps completed.
   * </pre>
   *
   * <code>int32 completed_steps = 2;</code>
   * @return The completedSteps.
   */
  @java.lang.Override
  public int getCompletedSteps() {
    return completedSteps_;
  }

  public static final int COMPLETED_PERCENT_FIELD_NUMBER = 3;
  private float completedPercent_ = 0F;
  /**
   * <pre>
   * The completed percentage for the tuning operation.
   * </pre>
   *
   * <code>float completed_percent = 3;</code>
   * @return The completedPercent.
   */
  @java.lang.Override
  public float getCompletedPercent() {
    return completedPercent_;
  }

  public static final int SNAPSHOTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.google.ai.generativelanguage.v1beta3.TuningSnapshot> snapshots_;
  /**
   * <pre>
   * Metrics collected during tuning.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.generativelanguage.v1beta3.TuningSnapshot> getSnapshotsList() {
    return snapshots_;
  }
  /**
   * <pre>
   * Metrics collected during tuning.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder> 
      getSnapshotsOrBuilderList() {
    return snapshots_;
  }
  /**
   * <pre>
   * Metrics collected during tuning.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
   */
  @java.lang.Override
  public int getSnapshotsCount() {
    return snapshots_.size();
  }
  /**
   * <pre>
   * Metrics collected during tuning.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TuningSnapshot getSnapshots(int index) {
    return snapshots_.get(index);
  }
  /**
   * <pre>
   * Metrics collected during tuning.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder getSnapshotsOrBuilder(
      int index) {
    return snapshots_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalSteps_ != 0) {
      output.writeInt32(1, totalSteps_);
    }
    if (completedSteps_ != 0) {
      output.writeInt32(2, completedSteps_);
    }
    if (java.lang.Float.floatToRawIntBits(completedPercent_) != 0) {
      output.writeFloat(3, completedPercent_);
    }
    for (int i = 0; i < snapshots_.size(); i++) {
      output.writeMessage(4, snapshots_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tunedModel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tunedModel_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalSteps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totalSteps_);
    }
    if (completedSteps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, completedSteps_);
    }
    if (java.lang.Float.floatToRawIntBits(completedPercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, completedPercent_);
    }
    for (int i = 0; i < snapshots_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, snapshots_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tunedModel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tunedModel_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata)) {
      return super.equals(obj);
    }
    com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata other = (com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata) obj;

    if (!getTunedModel()
        .equals(other.getTunedModel())) return false;
    if (getTotalSteps()
        != other.getTotalSteps()) return false;
    if (getCompletedSteps()
        != other.getCompletedSteps()) return false;
    if (java.lang.Float.floatToIntBits(getCompletedPercent())
        != java.lang.Float.floatToIntBits(
            other.getCompletedPercent())) return false;
    if (!getSnapshotsList()
        .equals(other.getSnapshotsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TUNED_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getTunedModel().hashCode();
    hash = (37 * hash) + TOTAL_STEPS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSteps();
    hash = (37 * hash) + COMPLETED_STEPS_FIELD_NUMBER;
    hash = (53 * hash) + getCompletedSteps();
    hash = (37 * hash) + COMPLETED_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCompletedPercent());
    if (getSnapshotsCount() > 0) {
      hash = (37 * hash) + SNAPSHOTS_FIELD_NUMBER;
      hash = (53 * hash) + getSnapshotsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata about the state and progress of creating a tuned model returned from
   * the long-running operation
   * </pre>
   *
   * Protobuf type {@code google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata)
      com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ai.generativelanguage.v1beta3.ModelServiceProto.internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ai.generativelanguage.v1beta3.ModelServiceProto.internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.class, com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.Builder.class);
    }

    // Construct using com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tunedModel_ = "";
      totalSteps_ = 0;
      completedSteps_ = 0;
      completedPercent_ = 0F;
      if (snapshotsBuilder_ == null) {
        snapshots_ = java.util.Collections.emptyList();
      } else {
        snapshots_ = null;
        snapshotsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ai.generativelanguage.v1beta3.ModelServiceProto.internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata getDefaultInstanceForType() {
      return com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata build() {
      com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata buildPartial() {
      com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata result = new com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata result) {
      if (snapshotsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          snapshots_ = java.util.Collections.unmodifiableList(snapshots_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.snapshots_ = snapshots_;
      } else {
        result.snapshots_ = snapshotsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tunedModel_ = tunedModel_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalSteps_ = totalSteps_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.completedSteps_ = completedSteps_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.completedPercent_ = completedPercent_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata) {
        return mergeFrom((com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata other) {
      if (other == com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata.getDefaultInstance()) return this;
      if (!other.getTunedModel().isEmpty()) {
        tunedModel_ = other.tunedModel_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTotalSteps() != 0) {
        setTotalSteps(other.getTotalSteps());
      }
      if (other.getCompletedSteps() != 0) {
        setCompletedSteps(other.getCompletedSteps());
      }
      if (other.getCompletedPercent() != 0F) {
        setCompletedPercent(other.getCompletedPercent());
      }
      if (snapshotsBuilder_ == null) {
        if (!other.snapshots_.isEmpty()) {
          if (snapshots_.isEmpty()) {
            snapshots_ = other.snapshots_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSnapshotsIsMutable();
            snapshots_.addAll(other.snapshots_);
          }
          onChanged();
        }
      } else {
        if (!other.snapshots_.isEmpty()) {
          if (snapshotsBuilder_.isEmpty()) {
            snapshotsBuilder_.dispose();
            snapshotsBuilder_ = null;
            snapshots_ = other.snapshots_;
            bitField0_ = (bitField0_ & ~0x00000010);
            snapshotsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSnapshotsFieldBuilder() : null;
          } else {
            snapshotsBuilder_.addAllMessages(other.snapshots_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              totalSteps_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 8
            case 16: {
              completedSteps_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 16
            case 29: {
              completedPercent_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 29
            case 34: {
              com.google.ai.generativelanguage.v1beta3.TuningSnapshot m =
                  input.readMessage(
                      com.google.ai.generativelanguage.v1beta3.TuningSnapshot.parser(),
                      extensionRegistry);
              if (snapshotsBuilder_ == null) {
                ensureSnapshotsIsMutable();
                snapshots_.add(m);
              } else {
                snapshotsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              tunedModel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tunedModel_ = "";
    /**
     * <pre>
     * Name of the tuned model associated with the tuning operation.
     * </pre>
     *
     * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
     * @return The tunedModel.
     */
    public java.lang.String getTunedModel() {
      java.lang.Object ref = tunedModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tunedModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the tuned model associated with the tuning operation.
     * </pre>
     *
     * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
     * @return The bytes for tunedModel.
     */
    public com.google.protobuf.ByteString
        getTunedModelBytes() {
      java.lang.Object ref = tunedModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tunedModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the tuned model associated with the tuning operation.
     * </pre>
     *
     * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
     * @param value The tunedModel to set.
     * @return This builder for chaining.
     */
    public Builder setTunedModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tunedModel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the tuned model associated with the tuning operation.
     * </pre>
     *
     * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTunedModel() {
      tunedModel_ = getDefaultInstance().getTunedModel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the tuned model associated with the tuning operation.
     * </pre>
     *
     * <code>string tuned_model = 5 [(.google.api.resource_reference) = { ... }</code>
     * @param value The bytes for tunedModel to set.
     * @return This builder for chaining.
     */
    public Builder setTunedModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tunedModel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int totalSteps_ ;
    /**
     * <pre>
     * The total number of tuning steps.
     * </pre>
     *
     * <code>int32 total_steps = 1;</code>
     * @return The totalSteps.
     */
    @java.lang.Override
    public int getTotalSteps() {
      return totalSteps_;
    }
    /**
     * <pre>
     * The total number of tuning steps.
     * </pre>
     *
     * <code>int32 total_steps = 1;</code>
     * @param value The totalSteps to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSteps(int value) {

      totalSteps_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The total number of tuning steps.
     * </pre>
     *
     * <code>int32 total_steps = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSteps() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalSteps_ = 0;
      onChanged();
      return this;
    }

    private int completedSteps_ ;
    /**
     * <pre>
     * The number of steps completed.
     * </pre>
     *
     * <code>int32 completed_steps = 2;</code>
     * @return The completedSteps.
     */
    @java.lang.Override
    public int getCompletedSteps() {
      return completedSteps_;
    }
    /**
     * <pre>
     * The number of steps completed.
     * </pre>
     *
     * <code>int32 completed_steps = 2;</code>
     * @param value The completedSteps to set.
     * @return This builder for chaining.
     */
    public Builder setCompletedSteps(int value) {

      completedSteps_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of steps completed.
     * </pre>
     *
     * <code>int32 completed_steps = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompletedSteps() {
      bitField0_ = (bitField0_ & ~0x00000004);
      completedSteps_ = 0;
      onChanged();
      return this;
    }

    private float completedPercent_ ;
    /**
     * <pre>
     * The completed percentage for the tuning operation.
     * </pre>
     *
     * <code>float completed_percent = 3;</code>
     * @return The completedPercent.
     */
    @java.lang.Override
    public float getCompletedPercent() {
      return completedPercent_;
    }
    /**
     * <pre>
     * The completed percentage for the tuning operation.
     * </pre>
     *
     * <code>float completed_percent = 3;</code>
     * @param value The completedPercent to set.
     * @return This builder for chaining.
     */
    public Builder setCompletedPercent(float value) {

      completedPercent_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The completed percentage for the tuning operation.
     * </pre>
     *
     * <code>float completed_percent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompletedPercent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      completedPercent_ = 0F;
      onChanged();
      return this;
    }

    private java.util.List<com.google.ai.generativelanguage.v1beta3.TuningSnapshot> snapshots_ =
      java.util.Collections.emptyList();
    private void ensureSnapshotsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        snapshots_ = new java.util.ArrayList<com.google.ai.generativelanguage.v1beta3.TuningSnapshot>(snapshots_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.TuningSnapshot, com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder, com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder> snapshotsBuilder_;

    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.TuningSnapshot> getSnapshotsList() {
      if (snapshotsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(snapshots_);
      } else {
        return snapshotsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public int getSnapshotsCount() {
      if (snapshotsBuilder_ == null) {
        return snapshots_.size();
      } else {
        return snapshotsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TuningSnapshot getSnapshots(int index) {
      if (snapshotsBuilder_ == null) {
        return snapshots_.get(index);
      } else {
        return snapshotsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder setSnapshots(
        int index, com.google.ai.generativelanguage.v1beta3.TuningSnapshot value) {
      if (snapshotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSnapshotsIsMutable();
        snapshots_.set(index, value);
        onChanged();
      } else {
        snapshotsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder setSnapshots(
        int index, com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder builderForValue) {
      if (snapshotsBuilder_ == null) {
        ensureSnapshotsIsMutable();
        snapshots_.set(index, builderForValue.build());
        onChanged();
      } else {
        snapshotsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder addSnapshots(com.google.ai.generativelanguage.v1beta3.TuningSnapshot value) {
      if (snapshotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSnapshotsIsMutable();
        snapshots_.add(value);
        onChanged();
      } else {
        snapshotsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder addSnapshots(
        int index, com.google.ai.generativelanguage.v1beta3.TuningSnapshot value) {
      if (snapshotsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSnapshotsIsMutable();
        snapshots_.add(index, value);
        onChanged();
      } else {
        snapshotsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder addSnapshots(
        com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder builderForValue) {
      if (snapshotsBuilder_ == null) {
        ensureSnapshotsIsMutable();
        snapshots_.add(builderForValue.build());
        onChanged();
      } else {
        snapshotsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder addSnapshots(
        int index, com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder builderForValue) {
      if (snapshotsBuilder_ == null) {
        ensureSnapshotsIsMutable();
        snapshots_.add(index, builderForValue.build());
        onChanged();
      } else {
        snapshotsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder addAllSnapshots(
        java.lang.Iterable<? extends com.google.ai.generativelanguage.v1beta3.TuningSnapshot> values) {
      if (snapshotsBuilder_ == null) {
        ensureSnapshotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, snapshots_);
        onChanged();
      } else {
        snapshotsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder clearSnapshots() {
      if (snapshotsBuilder_ == null) {
        snapshots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        snapshotsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public Builder removeSnapshots(int index) {
      if (snapshotsBuilder_ == null) {
        ensureSnapshotsIsMutable();
        snapshots_.remove(index);
        onChanged();
      } else {
        snapshotsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder getSnapshotsBuilder(
        int index) {
      return getSnapshotsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder getSnapshotsOrBuilder(
        int index) {
      if (snapshotsBuilder_ == null) {
        return snapshots_.get(index);  } else {
        return snapshotsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder> 
         getSnapshotsOrBuilderList() {
      if (snapshotsBuilder_ != null) {
        return snapshotsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(snapshots_);
      }
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder addSnapshotsBuilder() {
      return getSnapshotsFieldBuilder().addBuilder(
          com.google.ai.generativelanguage.v1beta3.TuningSnapshot.getDefaultInstance());
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder addSnapshotsBuilder(
        int index) {
      return getSnapshotsFieldBuilder().addBuilder(
          index, com.google.ai.generativelanguage.v1beta3.TuningSnapshot.getDefaultInstance());
    }
    /**
     * <pre>
     * Metrics collected during tuning.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TuningSnapshot snapshots = 4;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder> 
         getSnapshotsBuilderList() {
      return getSnapshotsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.TuningSnapshot, com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder, com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder> 
        getSnapshotsFieldBuilder() {
      if (snapshotsBuilder_ == null) {
        snapshotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.TuningSnapshot, com.google.ai.generativelanguage.v1beta3.TuningSnapshot.Builder, com.google.ai.generativelanguage.v1beta3.TuningSnapshotOrBuilder>(
                snapshots_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        snapshots_ = null;
      }
      return snapshotsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata)
  }

  // @@protoc_insertion_point(class_scope:google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata)
  private static final com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata();
  }

  public static com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTunedModelMetadata>
      PARSER = new com.google.protobuf.AbstractParser<CreateTunedModelMetadata>() {
    @java.lang.Override
    public CreateTunedModelMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTunedModelMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTunedModelMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.CreateTunedModelMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

