// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/discuss_service.proto

package com.google.ai.generativelanguage.v1beta3;

public final class DiscussServiceProto {
  private DiscussServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_MessagePrompt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_MessagePrompt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_Example_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_Example_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:google/ai/generativelanguage/v1beta3/d" +
      "iscuss_service.proto\022$google.ai.generati" +
      "velanguage.v1beta3\0323google/ai/generative" +
      "language/v1beta3/citation.proto\0321google/" +
      "ai/generativelanguage/v1beta3/safety.pro" +
      "to\032\034google/api/annotations.proto\032\027google" +
      "/api/client.proto\032\037google/api/field_beha" +
      "vior.proto\032\031google/api/resource.proto\"\324\002" +
      "\n\026GenerateMessageRequest\022?\n\005model\030\001 \001(\tB" +
      "0\342A\001\002\372A)\n\'generativelanguage.googleapis." +
      "com/Model\022I\n\006prompt\030\002 \001(\01323.google.ai.ge" +
      "nerativelanguage.v1beta3.MessagePromptB\004" +
      "\342A\001\002\022\036\n\013temperature\030\003 \001(\002B\004\342A\001\001H\000\210\001\001\022\"\n\017" +
      "candidate_count\030\004 \001(\005B\004\342A\001\001H\001\210\001\001\022\030\n\005top_" +
      "p\030\005 \001(\002B\004\342A\001\001H\002\210\001\001\022\030\n\005top_k\030\006 \001(\005B\004\342A\001\001H" +
      "\003\210\001\001B\016\n\014_temperatureB\022\n\020_candidate_count" +
      "B\010\n\006_top_pB\010\n\006_top_k\"\343\001\n\027GenerateMessage" +
      "Response\022A\n\ncandidates\030\001 \003(\0132-.google.ai" +
      ".generativelanguage.v1beta3.Message\022?\n\010m" +
      "essages\030\002 \003(\0132-.google.ai.generativelang" +
      "uage.v1beta3.Message\022D\n\007filters\030\003 \003(\01323." +
      "google.ai.generativelanguage.v1beta3.Con" +
      "tentFilter\"\252\001\n\007Message\022\024\n\006author\030\001 \001(\tB\004" +
      "\342A\001\001\022\025\n\007content\030\002 \001(\tB\004\342A\001\002\022\\\n\021citation_" +
      "metadata\030\003 \001(\01326.google.ai.generativelan" +
      "guage.v1beta3.CitationMetadataB\004\342A\001\003H\000\210\001" +
      "\001B\024\n\022_citation_metadata\"\264\001\n\rMessagePromp" +
      "t\022\025\n\007context\030\001 \001(\tB\004\342A\001\001\022E\n\010examples\030\002 \003" +
      "(\0132-.google.ai.generativelanguage.v1beta" +
      "3.ExampleB\004\342A\001\001\022E\n\010messages\030\003 \003(\0132-.goog" +
      "le.ai.generativelanguage.v1beta3.Message" +
      "B\004\342A\001\002\"\222\001\n\007Example\022B\n\005input\030\001 \001(\0132-.goog" +
      "le.ai.generativelanguage.v1beta3.Message" +
      "B\004\342A\001\002\022C\n\006output\030\002 \001(\0132-.google.ai.gener" +
      "ativelanguage.v1beta3.MessageB\004\342A\001\002\"\247\001\n\031" +
      "CountMessageTokensRequest\022?\n\005model\030\001 \001(\t" +
      "B0\342A\001\002\372A)\n\'generativelanguage.googleapis" +
      ".com/Model\022I\n\006prompt\030\002 \001(\01323.google.ai.g" +
      "enerativelanguage.v1beta3.MessagePromptB" +
      "\004\342A\001\002\"1\n\032CountMessageTokensResponse\022\023\n\013t" +
      "oken_count\030\001 \001(\0052\226\004\n\016DiscussService\022\373\001\n\017" +
      "GenerateMessage\022<.google.ai.generativela" +
      "nguage.v1beta3.GenerateMessageRequest\032=." +
      "google.ai.generativelanguage.v1beta3.Gen" +
      "erateMessageResponse\"k\332A4model,prompt,te" +
      "mperature,candidate_count,top_p,top_k\202\323\344" +
      "\223\002.\")/v1beta3/{model=models/*}:generateM" +
      "essage:\001*\022\337\001\n\022CountMessageTokens\022?.googl" +
      "e.ai.generativelanguage.v1beta3.CountMes" +
      "sageTokensRequest\032@.google.ai.generative" +
      "language.v1beta3.CountMessageTokensRespo" +
      "nse\"F\332A\014model,prompt\202\323\344\223\0021\",/v1beta3/{mo" +
      "del=models/*}:countMessageTokens:\001*\032$\312A!" +
      "generativelanguage.googleapis.comB\241\001\n(co" +
      "m.google.ai.generativelanguage.v1beta3B\023" +
      "DiscussServiceProtoP\001Z^cloud.google.com/" +
      "go/ai/generativelanguage/apiv1beta3/gene" +
      "rativelanguagepb;generativelanguagepbb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ai.generativelanguage.v1beta3.CitationProto.getDescriptor(),
          com.google.ai.generativelanguage.v1beta3.SafetyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
        });
    internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageRequest_descriptor,
        new java.lang.String[] { "Model", "Prompt", "Temperature", "CandidateCount", "TopP", "TopK", "Temperature", "CandidateCount", "TopP", "TopK", });
    internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_GenerateMessageResponse_descriptor,
        new java.lang.String[] { "Candidates", "Messages", "Filters", });
    internal_static_google_ai_generativelanguage_v1beta3_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ai_generativelanguage_v1beta3_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_Message_descriptor,
        new java.lang.String[] { "Author", "Content", "CitationMetadata", "CitationMetadata", });
    internal_static_google_ai_generativelanguage_v1beta3_MessagePrompt_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_ai_generativelanguage_v1beta3_MessagePrompt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_MessagePrompt_descriptor,
        new java.lang.String[] { "Context", "Examples", "Messages", });
    internal_static_google_ai_generativelanguage_v1beta3_Example_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_ai_generativelanguage_v1beta3_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_Example_descriptor,
        new java.lang.String[] { "Input", "Output", });
    internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensRequest_descriptor,
        new java.lang.String[] { "Model", "Prompt", });
    internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_CountMessageTokensResponse_descriptor,
        new java.lang.String[] { "TokenCount", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.ai.generativelanguage.v1beta3.CitationProto.getDescriptor();
    com.google.ai.generativelanguage.v1beta3.SafetyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
