// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/text_service.proto

package com.google.ai.generativelanguage.v1beta3;

/**
 * <pre>
 * The response from the model, including candidate completions.
 * </pre>
 *
 * Protobuf type {@code google.ai.generativelanguage.v1beta3.GenerateTextResponse}
 */
public final class GenerateTextResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.ai.generativelanguage.v1beta3.GenerateTextResponse)
    GenerateTextResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateTextResponse.newBuilder() to construct.
  private GenerateTextResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateTextResponse() {
    candidates_ = java.util.Collections.emptyList();
    filters_ = java.util.Collections.emptyList();
    safetyFeedback_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GenerateTextResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.class, com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.Builder.class);
  }

  public static final int CANDIDATES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.google.ai.generativelanguage.v1beta3.TextCompletion> candidates_;
  /**
   * <pre>
   * Candidate responses from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.generativelanguage.v1beta3.TextCompletion> getCandidatesList() {
    return candidates_;
  }
  /**
   * <pre>
   * Candidate responses from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder> 
      getCandidatesOrBuilderList() {
    return candidates_;
  }
  /**
   * <pre>
   * Candidate responses from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
   */
  @java.lang.Override
  public int getCandidatesCount() {
    return candidates_.size();
  }
  /**
   * <pre>
   * Candidate responses from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TextCompletion getCandidates(int index) {
    return candidates_.get(index);
  }
  /**
   * <pre>
   * Candidate responses from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder getCandidatesOrBuilder(
      int index) {
    return candidates_.get(index);
  }

  public static final int FILTERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.google.ai.generativelanguage.v1beta3.ContentFilter> filters_;
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   *
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   *
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.generativelanguage.v1beta3.ContentFilter> getFiltersList() {
    return filters_;
  }
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   *
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   *
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder> 
      getFiltersOrBuilderList() {
    return filters_;
  }
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   *
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   *
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
   */
  @java.lang.Override
  public int getFiltersCount() {
    return filters_.size();
  }
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   *
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   *
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.ContentFilter getFilters(int index) {
    return filters_.get(index);
  }
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   *
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   *
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder getFiltersOrBuilder(
      int index) {
    return filters_.get(index);
  }

  public static final int SAFETY_FEEDBACK_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyFeedback> safetyFeedback_;
  /**
   * <pre>
   * Returns any safety feedback related to content filtering.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyFeedback> getSafetyFeedbackList() {
    return safetyFeedback_;
  }
  /**
   * <pre>
   * Returns any safety feedback related to content filtering.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder> 
      getSafetyFeedbackOrBuilderList() {
    return safetyFeedback_;
  }
  /**
   * <pre>
   * Returns any safety feedback related to content filtering.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
   */
  @java.lang.Override
  public int getSafetyFeedbackCount() {
    return safetyFeedback_.size();
  }
  /**
   * <pre>
   * Returns any safety feedback related to content filtering.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.SafetyFeedback getSafetyFeedback(int index) {
    return safetyFeedback_.get(index);
  }
  /**
   * <pre>
   * Returns any safety feedback related to content filtering.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder getSafetyFeedbackOrBuilder(
      int index) {
    return safetyFeedback_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < candidates_.size(); i++) {
      output.writeMessage(1, candidates_.get(i));
    }
    for (int i = 0; i < filters_.size(); i++) {
      output.writeMessage(3, filters_.get(i));
    }
    for (int i = 0; i < safetyFeedback_.size(); i++) {
      output.writeMessage(4, safetyFeedback_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < candidates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, candidates_.get(i));
    }
    for (int i = 0; i < filters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, filters_.get(i));
    }
    for (int i = 0; i < safetyFeedback_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, safetyFeedback_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ai.generativelanguage.v1beta3.GenerateTextResponse)) {
      return super.equals(obj);
    }
    com.google.ai.generativelanguage.v1beta3.GenerateTextResponse other = (com.google.ai.generativelanguage.v1beta3.GenerateTextResponse) obj;

    if (!getCandidatesList()
        .equals(other.getCandidatesList())) return false;
    if (!getFiltersList()
        .equals(other.getFiltersList())) return false;
    if (!getSafetyFeedbackList()
        .equals(other.getSafetyFeedbackList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCandidatesCount() > 0) {
      hash = (37 * hash) + CANDIDATES_FIELD_NUMBER;
      hash = (53 * hash) + getCandidatesList().hashCode();
    }
    if (getFiltersCount() > 0) {
      hash = (37 * hash) + FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + getFiltersList().hashCode();
    }
    if (getSafetyFeedbackCount() > 0) {
      hash = (37 * hash) + SAFETY_FEEDBACK_FIELD_NUMBER;
      hash = (53 * hash) + getSafetyFeedbackList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ai.generativelanguage.v1beta3.GenerateTextResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response from the model, including candidate completions.
   * </pre>
   *
   * Protobuf type {@code google.ai.generativelanguage.v1beta3.GenerateTextResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.ai.generativelanguage.v1beta3.GenerateTextResponse)
      com.google.ai.generativelanguage.v1beta3.GenerateTextResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.class, com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.Builder.class);
    }

    // Construct using com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (candidatesBuilder_ == null) {
        candidates_ = java.util.Collections.emptyList();
      } else {
        candidates_ = null;
        candidatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (filtersBuilder_ == null) {
        filters_ = java.util.Collections.emptyList();
      } else {
        filters_ = null;
        filtersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (safetyFeedbackBuilder_ == null) {
        safetyFeedback_ = java.util.Collections.emptyList();
      } else {
        safetyFeedback_ = null;
        safetyFeedbackBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextResponse_descriptor;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.GenerateTextResponse getDefaultInstanceForType() {
      return com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.GenerateTextResponse build() {
      com.google.ai.generativelanguage.v1beta3.GenerateTextResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.GenerateTextResponse buildPartial() {
      com.google.ai.generativelanguage.v1beta3.GenerateTextResponse result = new com.google.ai.generativelanguage.v1beta3.GenerateTextResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.ai.generativelanguage.v1beta3.GenerateTextResponse result) {
      if (candidatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          candidates_ = java.util.Collections.unmodifiableList(candidates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.candidates_ = candidates_;
      } else {
        result.candidates_ = candidatesBuilder_.build();
      }
      if (filtersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          filters_ = java.util.Collections.unmodifiableList(filters_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.filters_ = filters_;
      } else {
        result.filters_ = filtersBuilder_.build();
      }
      if (safetyFeedbackBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          safetyFeedback_ = java.util.Collections.unmodifiableList(safetyFeedback_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.safetyFeedback_ = safetyFeedback_;
      } else {
        result.safetyFeedback_ = safetyFeedbackBuilder_.build();
      }
    }

    private void buildPartial0(com.google.ai.generativelanguage.v1beta3.GenerateTextResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ai.generativelanguage.v1beta3.GenerateTextResponse) {
        return mergeFrom((com.google.ai.generativelanguage.v1beta3.GenerateTextResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ai.generativelanguage.v1beta3.GenerateTextResponse other) {
      if (other == com.google.ai.generativelanguage.v1beta3.GenerateTextResponse.getDefaultInstance()) return this;
      if (candidatesBuilder_ == null) {
        if (!other.candidates_.isEmpty()) {
          if (candidates_.isEmpty()) {
            candidates_ = other.candidates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCandidatesIsMutable();
            candidates_.addAll(other.candidates_);
          }
          onChanged();
        }
      } else {
        if (!other.candidates_.isEmpty()) {
          if (candidatesBuilder_.isEmpty()) {
            candidatesBuilder_.dispose();
            candidatesBuilder_ = null;
            candidates_ = other.candidates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            candidatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCandidatesFieldBuilder() : null;
          } else {
            candidatesBuilder_.addAllMessages(other.candidates_);
          }
        }
      }
      if (filtersBuilder_ == null) {
        if (!other.filters_.isEmpty()) {
          if (filters_.isEmpty()) {
            filters_ = other.filters_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFiltersIsMutable();
            filters_.addAll(other.filters_);
          }
          onChanged();
        }
      } else {
        if (!other.filters_.isEmpty()) {
          if (filtersBuilder_.isEmpty()) {
            filtersBuilder_.dispose();
            filtersBuilder_ = null;
            filters_ = other.filters_;
            bitField0_ = (bitField0_ & ~0x00000002);
            filtersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFiltersFieldBuilder() : null;
          } else {
            filtersBuilder_.addAllMessages(other.filters_);
          }
        }
      }
      if (safetyFeedbackBuilder_ == null) {
        if (!other.safetyFeedback_.isEmpty()) {
          if (safetyFeedback_.isEmpty()) {
            safetyFeedback_ = other.safetyFeedback_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSafetyFeedbackIsMutable();
            safetyFeedback_.addAll(other.safetyFeedback_);
          }
          onChanged();
        }
      } else {
        if (!other.safetyFeedback_.isEmpty()) {
          if (safetyFeedbackBuilder_.isEmpty()) {
            safetyFeedbackBuilder_.dispose();
            safetyFeedbackBuilder_ = null;
            safetyFeedback_ = other.safetyFeedback_;
            bitField0_ = (bitField0_ & ~0x00000004);
            safetyFeedbackBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSafetyFeedbackFieldBuilder() : null;
          } else {
            safetyFeedbackBuilder_.addAllMessages(other.safetyFeedback_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.ai.generativelanguage.v1beta3.TextCompletion m =
                  input.readMessage(
                      com.google.ai.generativelanguage.v1beta3.TextCompletion.parser(),
                      extensionRegistry);
              if (candidatesBuilder_ == null) {
                ensureCandidatesIsMutable();
                candidates_.add(m);
              } else {
                candidatesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 26: {
              com.google.ai.generativelanguage.v1beta3.ContentFilter m =
                  input.readMessage(
                      com.google.ai.generativelanguage.v1beta3.ContentFilter.parser(),
                      extensionRegistry);
              if (filtersBuilder_ == null) {
                ensureFiltersIsMutable();
                filters_.add(m);
              } else {
                filtersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.google.ai.generativelanguage.v1beta3.SafetyFeedback m =
                  input.readMessage(
                      com.google.ai.generativelanguage.v1beta3.SafetyFeedback.parser(),
                      extensionRegistry);
              if (safetyFeedbackBuilder_ == null) {
                ensureSafetyFeedbackIsMutable();
                safetyFeedback_.add(m);
              } else {
                safetyFeedbackBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.ai.generativelanguage.v1beta3.TextCompletion> candidates_ =
      java.util.Collections.emptyList();
    private void ensureCandidatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        candidates_ = new java.util.ArrayList<com.google.ai.generativelanguage.v1beta3.TextCompletion>(candidates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.TextCompletion, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder, com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder> candidatesBuilder_;

    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.TextCompletion> getCandidatesList() {
      if (candidatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(candidates_);
      } else {
        return candidatesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public int getCandidatesCount() {
      if (candidatesBuilder_ == null) {
        return candidates_.size();
      } else {
        return candidatesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextCompletion getCandidates(int index) {
      if (candidatesBuilder_ == null) {
        return candidates_.get(index);
      } else {
        return candidatesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder setCandidates(
        int index, com.google.ai.generativelanguage.v1beta3.TextCompletion value) {
      if (candidatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidatesIsMutable();
        candidates_.set(index, value);
        onChanged();
      } else {
        candidatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder setCandidates(
        int index, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder builderForValue) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.set(index, builderForValue.build());
        onChanged();
      } else {
        candidatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder addCandidates(com.google.ai.generativelanguage.v1beta3.TextCompletion value) {
      if (candidatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidatesIsMutable();
        candidates_.add(value);
        onChanged();
      } else {
        candidatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder addCandidates(
        int index, com.google.ai.generativelanguage.v1beta3.TextCompletion value) {
      if (candidatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidatesIsMutable();
        candidates_.add(index, value);
        onChanged();
      } else {
        candidatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder addCandidates(
        com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder builderForValue) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.add(builderForValue.build());
        onChanged();
      } else {
        candidatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder addCandidates(
        int index, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder builderForValue) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.add(index, builderForValue.build());
        onChanged();
      } else {
        candidatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder addAllCandidates(
        java.lang.Iterable<? extends com.google.ai.generativelanguage.v1beta3.TextCompletion> values) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, candidates_);
        onChanged();
      } else {
        candidatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder clearCandidates() {
      if (candidatesBuilder_ == null) {
        candidates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        candidatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public Builder removeCandidates(int index) {
      if (candidatesBuilder_ == null) {
        ensureCandidatesIsMutable();
        candidates_.remove(index);
        onChanged();
      } else {
        candidatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder getCandidatesBuilder(
        int index) {
      return getCandidatesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder getCandidatesOrBuilder(
        int index) {
      if (candidatesBuilder_ == null) {
        return candidates_.get(index);  } else {
        return candidatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder> 
         getCandidatesOrBuilderList() {
      if (candidatesBuilder_ != null) {
        return candidatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(candidates_);
      }
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder addCandidatesBuilder() {
      return getCandidatesFieldBuilder().addBuilder(
          com.google.ai.generativelanguage.v1beta3.TextCompletion.getDefaultInstance());
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder addCandidatesBuilder(
        int index) {
      return getCandidatesFieldBuilder().addBuilder(
          index, com.google.ai.generativelanguage.v1beta3.TextCompletion.getDefaultInstance());
    }
    /**
     * <pre>
     * Candidate responses from the model.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.TextCompletion candidates = 1;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder> 
         getCandidatesBuilderList() {
      return getCandidatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.TextCompletion, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder, com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder> 
        getCandidatesFieldBuilder() {
      if (candidatesBuilder_ == null) {
        candidatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.TextCompletion, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder, com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder>(
                candidates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        candidates_ = null;
      }
      return candidatesBuilder_;
    }

    private java.util.List<com.google.ai.generativelanguage.v1beta3.ContentFilter> filters_ =
      java.util.Collections.emptyList();
    private void ensureFiltersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        filters_ = new java.util.ArrayList<com.google.ai.generativelanguage.v1beta3.ContentFilter>(filters_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.ContentFilter, com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder, com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder> filtersBuilder_;

    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.ContentFilter> getFiltersList() {
      if (filtersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(filters_);
      } else {
        return filtersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public int getFiltersCount() {
      if (filtersBuilder_ == null) {
        return filters_.size();
      } else {
        return filtersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.ContentFilter getFilters(int index) {
      if (filtersBuilder_ == null) {
        return filters_.get(index);
      } else {
        return filtersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder setFilters(
        int index, com.google.ai.generativelanguage.v1beta3.ContentFilter value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFiltersIsMutable();
        filters_.set(index, value);
        onChanged();
      } else {
        filtersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder setFilters(
        int index, com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.set(index, builderForValue.build());
        onChanged();
      } else {
        filtersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder addFilters(com.google.ai.generativelanguage.v1beta3.ContentFilter value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFiltersIsMutable();
        filters_.add(value);
        onChanged();
      } else {
        filtersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder addFilters(
        int index, com.google.ai.generativelanguage.v1beta3.ContentFilter value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFiltersIsMutable();
        filters_.add(index, value);
        onChanged();
      } else {
        filtersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder addFilters(
        com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.add(builderForValue.build());
        onChanged();
      } else {
        filtersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder addFilters(
        int index, com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.add(index, builderForValue.build());
        onChanged();
      } else {
        filtersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder addAllFilters(
        java.lang.Iterable<? extends com.google.ai.generativelanguage.v1beta3.ContentFilter> values) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, filters_);
        onChanged();
      } else {
        filtersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder clearFilters() {
      if (filtersBuilder_ == null) {
        filters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        filtersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public Builder removeFilters(int index) {
      if (filtersBuilder_ == null) {
        ensureFiltersIsMutable();
        filters_.remove(index);
        onChanged();
      } else {
        filtersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder getFiltersBuilder(
        int index) {
      return getFiltersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder getFiltersOrBuilder(
        int index) {
      if (filtersBuilder_ == null) {
        return filters_.get(index);  } else {
        return filtersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder> 
         getFiltersOrBuilderList() {
      if (filtersBuilder_ != null) {
        return filtersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(filters_);
      }
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder addFiltersBuilder() {
      return getFiltersFieldBuilder().addBuilder(
          com.google.ai.generativelanguage.v1beta3.ContentFilter.getDefaultInstance());
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder addFiltersBuilder(
        int index) {
      return getFiltersFieldBuilder().addBuilder(
          index, com.google.ai.generativelanguage.v1beta3.ContentFilter.getDefaultInstance());
    }
    /**
     * <pre>
     * A set of content filtering metadata for the prompt and response
     * text.
     *
     * This indicates which `SafetyCategory`(s) blocked a
     * candidate from this response, the lowest `HarmProbability`
     * that triggered a block, and the HarmThreshold setting for that category.
     * This indicates the smallest change to the `SafetySettings` that would be
     * necessary to unblock at least 1 response.
     *
     * The blocking is configured by the `SafetySettings` in the request (or the
     * default `SafetySettings` of the API).
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.ContentFilter filters = 3;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder> 
         getFiltersBuilderList() {
      return getFiltersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.ContentFilter, com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder, com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder> 
        getFiltersFieldBuilder() {
      if (filtersBuilder_ == null) {
        filtersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.ContentFilter, com.google.ai.generativelanguage.v1beta3.ContentFilter.Builder, com.google.ai.generativelanguage.v1beta3.ContentFilterOrBuilder>(
                filters_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        filters_ = null;
      }
      return filtersBuilder_;
    }

    private java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyFeedback> safetyFeedback_ =
      java.util.Collections.emptyList();
    private void ensureSafetyFeedbackIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        safetyFeedback_ = new java.util.ArrayList<com.google.ai.generativelanguage.v1beta3.SafetyFeedback>(safetyFeedback_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.SafetyFeedback, com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder, com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder> safetyFeedbackBuilder_;

    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyFeedback> getSafetyFeedbackList() {
      if (safetyFeedbackBuilder_ == null) {
        return java.util.Collections.unmodifiableList(safetyFeedback_);
      } else {
        return safetyFeedbackBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public int getSafetyFeedbackCount() {
      if (safetyFeedbackBuilder_ == null) {
        return safetyFeedback_.size();
      } else {
        return safetyFeedbackBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyFeedback getSafetyFeedback(int index) {
      if (safetyFeedbackBuilder_ == null) {
        return safetyFeedback_.get(index);
      } else {
        return safetyFeedbackBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder setSafetyFeedback(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyFeedback value) {
      if (safetyFeedbackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.set(index, value);
        onChanged();
      } else {
        safetyFeedbackBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder setSafetyFeedback(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder builderForValue) {
      if (safetyFeedbackBuilder_ == null) {
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.set(index, builderForValue.build());
        onChanged();
      } else {
        safetyFeedbackBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder addSafetyFeedback(com.google.ai.generativelanguage.v1beta3.SafetyFeedback value) {
      if (safetyFeedbackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.add(value);
        onChanged();
      } else {
        safetyFeedbackBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder addSafetyFeedback(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyFeedback value) {
      if (safetyFeedbackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.add(index, value);
        onChanged();
      } else {
        safetyFeedbackBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder addSafetyFeedback(
        com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder builderForValue) {
      if (safetyFeedbackBuilder_ == null) {
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.add(builderForValue.build());
        onChanged();
      } else {
        safetyFeedbackBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder addSafetyFeedback(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder builderForValue) {
      if (safetyFeedbackBuilder_ == null) {
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.add(index, builderForValue.build());
        onChanged();
      } else {
        safetyFeedbackBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder addAllSafetyFeedback(
        java.lang.Iterable<? extends com.google.ai.generativelanguage.v1beta3.SafetyFeedback> values) {
      if (safetyFeedbackBuilder_ == null) {
        ensureSafetyFeedbackIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, safetyFeedback_);
        onChanged();
      } else {
        safetyFeedbackBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder clearSafetyFeedback() {
      if (safetyFeedbackBuilder_ == null) {
        safetyFeedback_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        safetyFeedbackBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public Builder removeSafetyFeedback(int index) {
      if (safetyFeedbackBuilder_ == null) {
        ensureSafetyFeedbackIsMutable();
        safetyFeedback_.remove(index);
        onChanged();
      } else {
        safetyFeedbackBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder getSafetyFeedbackBuilder(
        int index) {
      return getSafetyFeedbackFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder getSafetyFeedbackOrBuilder(
        int index) {
      if (safetyFeedbackBuilder_ == null) {
        return safetyFeedback_.get(index);  } else {
        return safetyFeedbackBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder> 
         getSafetyFeedbackOrBuilderList() {
      if (safetyFeedbackBuilder_ != null) {
        return safetyFeedbackBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(safetyFeedback_);
      }
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder addSafetyFeedbackBuilder() {
      return getSafetyFeedbackFieldBuilder().addBuilder(
          com.google.ai.generativelanguage.v1beta3.SafetyFeedback.getDefaultInstance());
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder addSafetyFeedbackBuilder(
        int index) {
      return getSafetyFeedbackFieldBuilder().addBuilder(
          index, com.google.ai.generativelanguage.v1beta3.SafetyFeedback.getDefaultInstance());
    }
    /**
     * <pre>
     * Returns any safety feedback related to content filtering.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyFeedback safety_feedback = 4;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder> 
         getSafetyFeedbackBuilderList() {
      return getSafetyFeedbackFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.SafetyFeedback, com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder, com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder> 
        getSafetyFeedbackFieldBuilder() {
      if (safetyFeedbackBuilder_ == null) {
        safetyFeedbackBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.SafetyFeedback, com.google.ai.generativelanguage.v1beta3.SafetyFeedback.Builder, com.google.ai.generativelanguage.v1beta3.SafetyFeedbackOrBuilder>(
                safetyFeedback_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        safetyFeedback_ = null;
      }
      return safetyFeedbackBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.ai.generativelanguage.v1beta3.GenerateTextResponse)
  }

  // @@protoc_insertion_point(class_scope:google.ai.generativelanguage.v1beta3.GenerateTextResponse)
  private static final com.google.ai.generativelanguage.v1beta3.GenerateTextResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ai.generativelanguage.v1beta3.GenerateTextResponse();
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateTextResponse>
      PARSER = new com.google.protobuf.AbstractParser<GenerateTextResponse>() {
    @java.lang.Override
    public GenerateTextResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GenerateTextResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateTextResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.GenerateTextResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

