// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/text_service.proto

package com.google.ai.generativelanguage.v1beta3;

/**
 * <pre>
 * Request to generate a text completion response from the model.
 * </pre>
 *
 * Protobuf type {@code google.ai.generativelanguage.v1beta3.GenerateTextRequest}
 */
public final class GenerateTextRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.ai.generativelanguage.v1beta3.GenerateTextRequest)
    GenerateTextRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateTextRequest.newBuilder() to construct.
  private GenerateTextRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateTextRequest() {
    model_ = "";
    safetySettings_ = java.util.Collections.emptyList();
    stopSequences_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GenerateTextRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.class, com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.Builder.class);
  }

  private int bitField0_;
  public static final int MODEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object model_ = "";
  /**
   * <pre>
   * Required. The name of the `Model` or `TunedModel` to use for generating the
   * completion.
   * Examples:
   *  models/text-bison-001
   *  tunedModels/sentence-translator-u3b7m
   * </pre>
   *
   * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The name of the `Model` or `TunedModel` to use for generating the
   * completion.
   * Examples:
   *  models/text-bison-001
   *  tunedModels/sentence-translator-u3b7m
   * </pre>
   *
   * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROMPT_FIELD_NUMBER = 2;
  private com.google.ai.generativelanguage.v1beta3.TextPrompt prompt_;
  /**
   * <pre>
   * Required. The free-form input text given to the model as a prompt.
   *
   * Given a prompt, the model will generate a TextCompletion response it
   * predicts as the completion of the input text.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the prompt field is set.
   */
  @java.lang.Override
  public boolean hasPrompt() {
    return prompt_ != null;
  }
  /**
   * <pre>
   * Required. The free-form input text given to the model as a prompt.
   *
   * Given a prompt, the model will generate a TextCompletion response it
   * predicts as the completion of the input text.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The prompt.
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TextPrompt getPrompt() {
    return prompt_ == null ? com.google.ai.generativelanguage.v1beta3.TextPrompt.getDefaultInstance() : prompt_;
  }
  /**
   * <pre>
   * Required. The free-form input text given to the model as a prompt.
   *
   * Given a prompt, the model will generate a TextCompletion response it
   * predicts as the completion of the input text.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TextPromptOrBuilder getPromptOrBuilder() {
    return prompt_ == null ? com.google.ai.generativelanguage.v1beta3.TextPrompt.getDefaultInstance() : prompt_;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 3;
  private float temperature_ = 0F;
  /**
   * <pre>
   * Optional. Controls the randomness of the output.
   * Note: The default value varies by model, see the `Model.temperature`
   * attribute of the `Model` returned the `getModel` function.
   *
   * Values can range from [0.0,1.0],
   * inclusive. A value closer to 1.0 will produce responses that are more
   * varied and creative, while a value closer to 0.0 will typically result in
   * more straightforward responses from the model.
   * </pre>
   *
   * <code>optional float temperature = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the temperature field is set.
   */
  @java.lang.Override
  public boolean hasTemperature() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional. Controls the randomness of the output.
   * Note: The default value varies by model, see the `Model.temperature`
   * attribute of the `Model` returned the `getModel` function.
   *
   * Values can range from [0.0,1.0],
   * inclusive. A value closer to 1.0 will produce responses that are more
   * varied and creative, while a value closer to 0.0 will typically result in
   * more straightforward responses from the model.
   * </pre>
   *
   * <code>optional float temperature = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int CANDIDATE_COUNT_FIELD_NUMBER = 4;
  private int candidateCount_ = 0;
  /**
   * <pre>
   * Optional. Number of generated responses to return.
   *
   * This value must be between [1, 8], inclusive. If unset, this will default
   * to 1.
   * </pre>
   *
   * <code>optional int32 candidate_count = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the candidateCount field is set.
   */
  @java.lang.Override
  public boolean hasCandidateCount() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Optional. Number of generated responses to return.
   *
   * This value must be between [1, 8], inclusive. If unset, this will default
   * to 1.
   * </pre>
   *
   * <code>optional int32 candidate_count = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The candidateCount.
   */
  @java.lang.Override
  public int getCandidateCount() {
    return candidateCount_;
  }

  public static final int MAX_OUTPUT_TOKENS_FIELD_NUMBER = 5;
  private int maxOutputTokens_ = 0;
  /**
   * <pre>
   * Optional. The maximum number of tokens to include in a candidate.
   *
   * If unset, this will default to output_token_limit specified in the `Model`
   * specification.
   * </pre>
   *
   * <code>optional int32 max_output_tokens = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the maxOutputTokens field is set.
   */
  @java.lang.Override
  public boolean hasMaxOutputTokens() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Optional. The maximum number of tokens to include in a candidate.
   *
   * If unset, this will default to output_token_limit specified in the `Model`
   * specification.
   * </pre>
   *
   * <code>optional int32 max_output_tokens = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The maxOutputTokens.
   */
  @java.lang.Override
  public int getMaxOutputTokens() {
    return maxOutputTokens_;
  }

  public static final int TOP_P_FIELD_NUMBER = 6;
  private float topP_ = 0F;
  /**
   * <pre>
   * Optional. The maximum cumulative probability of tokens to consider when
   * sampling.
   *
   * The model uses combined Top-k and nucleus sampling.
   *
   * Tokens are sorted based on their assigned probabilities so that only the
   * most likely tokens are considered. Top-k sampling directly limits the
   * maximum number of tokens to consider, while Nucleus sampling limits number
   * of tokens based on the cumulative probability.
   *
   * Note: The default value varies by model, see the `Model.top_p`
   * attribute of the `Model` returned the `getModel` function.
   * </pre>
   *
   * <code>optional float top_p = 6 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the topP field is set.
   */
  @java.lang.Override
  public boolean hasTopP() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Optional. The maximum cumulative probability of tokens to consider when
   * sampling.
   *
   * The model uses combined Top-k and nucleus sampling.
   *
   * Tokens are sorted based on their assigned probabilities so that only the
   * most likely tokens are considered. Top-k sampling directly limits the
   * maximum number of tokens to consider, while Nucleus sampling limits number
   * of tokens based on the cumulative probability.
   *
   * Note: The default value varies by model, see the `Model.top_p`
   * attribute of the `Model` returned the `getModel` function.
   * </pre>
   *
   * <code>optional float top_p = 6 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The topP.
   */
  @java.lang.Override
  public float getTopP() {
    return topP_;
  }

  public static final int TOP_K_FIELD_NUMBER = 7;
  private int topK_ = 0;
  /**
   * <pre>
   * Optional. The maximum number of tokens to consider when sampling.
   *
   * The model uses combined Top-k and nucleus sampling.
   *
   * Top-k sampling considers the set of `top_k` most probable tokens.
   * Defaults to 40.
   *
   * Note: The default value varies by model, see the `Model.top_k`
   * attribute of the `Model` returned the `getModel` function.
   * </pre>
   *
   * <code>optional int32 top_k = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the topK field is set.
   */
  @java.lang.Override
  public boolean hasTopK() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Optional. The maximum number of tokens to consider when sampling.
   *
   * The model uses combined Top-k and nucleus sampling.
   *
   * Top-k sampling considers the set of `top_k` most probable tokens.
   * Defaults to 40.
   *
   * Note: The default value varies by model, see the `Model.top_k`
   * attribute of the `Model` returned the `getModel` function.
   * </pre>
   *
   * <code>optional int32 top_k = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The topK.
   */
  @java.lang.Override
  public int getTopK() {
    return topK_;
  }

  public static final int SAFETY_SETTINGS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<com.google.ai.generativelanguage.v1beta3.SafetySetting> safetySettings_;
  /**
   * <pre>
   * A list of unique `SafetySetting` instances for blocking unsafe content.
   *
   * that will be enforced on the `GenerateTextRequest.prompt` and
   * `GenerateTextResponse.candidates`. There should not be more than one
   * setting for each `SafetyCategory` type. The API will block any prompts and
   * responses that fail to meet the thresholds set by these settings. This list
   * overrides the default settings for each `SafetyCategory` specified in the
   * safety_settings. If there is no `SafetySetting` for a given
   * `SafetyCategory` provided in the list, the API will use the default safety
   * setting for that category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetySetting> getSafetySettingsList() {
    return safetySettings_;
  }
  /**
   * <pre>
   * A list of unique `SafetySetting` instances for blocking unsafe content.
   *
   * that will be enforced on the `GenerateTextRequest.prompt` and
   * `GenerateTextResponse.candidates`. There should not be more than one
   * setting for each `SafetyCategory` type. The API will block any prompts and
   * responses that fail to meet the thresholds set by these settings. This list
   * overrides the default settings for each `SafetyCategory` specified in the
   * safety_settings. If there is no `SafetySetting` for a given
   * `SafetyCategory` provided in the list, the API will use the default safety
   * setting for that category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder> 
      getSafetySettingsOrBuilderList() {
    return safetySettings_;
  }
  /**
   * <pre>
   * A list of unique `SafetySetting` instances for blocking unsafe content.
   *
   * that will be enforced on the `GenerateTextRequest.prompt` and
   * `GenerateTextResponse.candidates`. There should not be more than one
   * setting for each `SafetyCategory` type. The API will block any prompts and
   * responses that fail to meet the thresholds set by these settings. This list
   * overrides the default settings for each `SafetyCategory` specified in the
   * safety_settings. If there is no `SafetySetting` for a given
   * `SafetyCategory` provided in the list, the API will use the default safety
   * setting for that category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
   */
  @java.lang.Override
  public int getSafetySettingsCount() {
    return safetySettings_.size();
  }
  /**
   * <pre>
   * A list of unique `SafetySetting` instances for blocking unsafe content.
   *
   * that will be enforced on the `GenerateTextRequest.prompt` and
   * `GenerateTextResponse.candidates`. There should not be more than one
   * setting for each `SafetyCategory` type. The API will block any prompts and
   * responses that fail to meet the thresholds set by these settings. This list
   * overrides the default settings for each `SafetyCategory` specified in the
   * safety_settings. If there is no `SafetySetting` for a given
   * `SafetyCategory` provided in the list, the API will use the default safety
   * setting for that category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.SafetySetting getSafetySettings(int index) {
    return safetySettings_.get(index);
  }
  /**
   * <pre>
   * A list of unique `SafetySetting` instances for blocking unsafe content.
   *
   * that will be enforced on the `GenerateTextRequest.prompt` and
   * `GenerateTextResponse.candidates`. There should not be more than one
   * setting for each `SafetyCategory` type. The API will block any prompts and
   * responses that fail to meet the thresholds set by these settings. This list
   * overrides the default settings for each `SafetyCategory` specified in the
   * safety_settings. If there is no `SafetySetting` for a given
   * `SafetyCategory` provided in the list, the API will use the default safety
   * setting for that category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder getSafetySettingsOrBuilder(
      int index) {
    return safetySettings_.get(index);
  }

  public static final int STOP_SEQUENCES_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList stopSequences_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The set of character sequences (up to 5) that will stop output generation.
   * If specified, the API will stop at the first appearance of a stop
   * sequence. The stop sequence will not be included as part of the response.
   * </pre>
   *
   * <code>repeated string stop_sequences = 9;</code>
   * @return A list containing the stopSequences.
   */
  public com.google.protobuf.ProtocolStringList
      getStopSequencesList() {
    return stopSequences_;
  }
  /**
   * <pre>
   * The set of character sequences (up to 5) that will stop output generation.
   * If specified, the API will stop at the first appearance of a stop
   * sequence. The stop sequence will not be included as part of the response.
   * </pre>
   *
   * <code>repeated string stop_sequences = 9;</code>
   * @return The count of stopSequences.
   */
  public int getStopSequencesCount() {
    return stopSequences_.size();
  }
  /**
   * <pre>
   * The set of character sequences (up to 5) that will stop output generation.
   * If specified, the API will stop at the first appearance of a stop
   * sequence. The stop sequence will not be included as part of the response.
   * </pre>
   *
   * <code>repeated string stop_sequences = 9;</code>
   * @param index The index of the element to return.
   * @return The stopSequences at the given index.
   */
  public java.lang.String getStopSequences(int index) {
    return stopSequences_.get(index);
  }
  /**
   * <pre>
   * The set of character sequences (up to 5) that will stop output generation.
   * If specified, the API will stop at the first appearance of a stop
   * sequence. The stop sequence will not be included as part of the response.
   * </pre>
   *
   * <code>repeated string stop_sequences = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stopSequences at the given index.
   */
  public com.google.protobuf.ByteString
      getStopSequencesBytes(int index) {
    return stopSequences_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, model_);
    }
    if (prompt_ != null) {
      output.writeMessage(2, getPrompt());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeFloat(3, temperature_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(4, candidateCount_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(5, maxOutputTokens_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeFloat(6, topP_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(7, topK_);
    }
    for (int i = 0; i < safetySettings_.size(); i++) {
      output.writeMessage(8, safetySettings_.get(i));
    }
    for (int i = 0; i < stopSequences_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, stopSequences_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, model_);
    }
    if (prompt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPrompt());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, temperature_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, candidateCount_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxOutputTokens_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, topP_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, topK_);
    }
    for (int i = 0; i < safetySettings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, safetySettings_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stopSequences_.size(); i++) {
        dataSize += computeStringSizeNoTag(stopSequences_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStopSequencesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ai.generativelanguage.v1beta3.GenerateTextRequest)) {
      return super.equals(obj);
    }
    com.google.ai.generativelanguage.v1beta3.GenerateTextRequest other = (com.google.ai.generativelanguage.v1beta3.GenerateTextRequest) obj;

    if (!getModel()
        .equals(other.getModel())) return false;
    if (hasPrompt() != other.hasPrompt()) return false;
    if (hasPrompt()) {
      if (!getPrompt()
          .equals(other.getPrompt())) return false;
    }
    if (hasTemperature() != other.hasTemperature()) return false;
    if (hasTemperature()) {
      if (java.lang.Float.floatToIntBits(getTemperature())
          != java.lang.Float.floatToIntBits(
              other.getTemperature())) return false;
    }
    if (hasCandidateCount() != other.hasCandidateCount()) return false;
    if (hasCandidateCount()) {
      if (getCandidateCount()
          != other.getCandidateCount()) return false;
    }
    if (hasMaxOutputTokens() != other.hasMaxOutputTokens()) return false;
    if (hasMaxOutputTokens()) {
      if (getMaxOutputTokens()
          != other.getMaxOutputTokens()) return false;
    }
    if (hasTopP() != other.hasTopP()) return false;
    if (hasTopP()) {
      if (java.lang.Float.floatToIntBits(getTopP())
          != java.lang.Float.floatToIntBits(
              other.getTopP())) return false;
    }
    if (hasTopK() != other.hasTopK()) return false;
    if (hasTopK()) {
      if (getTopK()
          != other.getTopK()) return false;
    }
    if (!getSafetySettingsList()
        .equals(other.getSafetySettingsList())) return false;
    if (!getStopSequencesList()
        .equals(other.getStopSequencesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    if (hasPrompt()) {
      hash = (37 * hash) + PROMPT_FIELD_NUMBER;
      hash = (53 * hash) + getPrompt().hashCode();
    }
    if (hasTemperature()) {
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
    }
    if (hasCandidateCount()) {
      hash = (37 * hash) + CANDIDATE_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateCount();
    }
    if (hasMaxOutputTokens()) {
      hash = (37 * hash) + MAX_OUTPUT_TOKENS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxOutputTokens();
    }
    if (hasTopP()) {
      hash = (37 * hash) + TOP_P_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTopP());
    }
    if (hasTopK()) {
      hash = (37 * hash) + TOP_K_FIELD_NUMBER;
      hash = (53 * hash) + getTopK();
    }
    if (getSafetySettingsCount() > 0) {
      hash = (37 * hash) + SAFETY_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSafetySettingsList().hashCode();
    }
    if (getStopSequencesCount() > 0) {
      hash = (37 * hash) + STOP_SEQUENCES_FIELD_NUMBER;
      hash = (53 * hash) + getStopSequencesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ai.generativelanguage.v1beta3.GenerateTextRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to generate a text completion response from the model.
   * </pre>
   *
   * Protobuf type {@code google.ai.generativelanguage.v1beta3.GenerateTextRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.ai.generativelanguage.v1beta3.GenerateTextRequest)
      com.google.ai.generativelanguage.v1beta3.GenerateTextRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.class, com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.Builder.class);
    }

    // Construct using com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      model_ = "";
      prompt_ = null;
      if (promptBuilder_ != null) {
        promptBuilder_.dispose();
        promptBuilder_ = null;
      }
      temperature_ = 0F;
      candidateCount_ = 0;
      maxOutputTokens_ = 0;
      topP_ = 0F;
      topK_ = 0;
      if (safetySettingsBuilder_ == null) {
        safetySettings_ = java.util.Collections.emptyList();
      } else {
        safetySettings_ = null;
        safetySettingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      stopSequences_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_GenerateTextRequest_descriptor;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.GenerateTextRequest getDefaultInstanceForType() {
      return com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.GenerateTextRequest build() {
      com.google.ai.generativelanguage.v1beta3.GenerateTextRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.GenerateTextRequest buildPartial() {
      com.google.ai.generativelanguage.v1beta3.GenerateTextRequest result = new com.google.ai.generativelanguage.v1beta3.GenerateTextRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.ai.generativelanguage.v1beta3.GenerateTextRequest result) {
      if (safetySettingsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          safetySettings_ = java.util.Collections.unmodifiableList(safetySettings_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.safetySettings_ = safetySettings_;
      } else {
        result.safetySettings_ = safetySettingsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.ai.generativelanguage.v1beta3.GenerateTextRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.model_ = model_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.prompt_ = promptBuilder_ == null
            ? prompt_
            : promptBuilder_.build();
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.temperature_ = temperature_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.candidateCount_ = candidateCount_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxOutputTokens_ = maxOutputTokens_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.topP_ = topP_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.topK_ = topK_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        stopSequences_.makeImmutable();
        result.stopSequences_ = stopSequences_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ai.generativelanguage.v1beta3.GenerateTextRequest) {
        return mergeFrom((com.google.ai.generativelanguage.v1beta3.GenerateTextRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ai.generativelanguage.v1beta3.GenerateTextRequest other) {
      if (other == com.google.ai.generativelanguage.v1beta3.GenerateTextRequest.getDefaultInstance()) return this;
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPrompt()) {
        mergePrompt(other.getPrompt());
      }
      if (other.hasTemperature()) {
        setTemperature(other.getTemperature());
      }
      if (other.hasCandidateCount()) {
        setCandidateCount(other.getCandidateCount());
      }
      if (other.hasMaxOutputTokens()) {
        setMaxOutputTokens(other.getMaxOutputTokens());
      }
      if (other.hasTopP()) {
        setTopP(other.getTopP());
      }
      if (other.hasTopK()) {
        setTopK(other.getTopK());
      }
      if (safetySettingsBuilder_ == null) {
        if (!other.safetySettings_.isEmpty()) {
          if (safetySettings_.isEmpty()) {
            safetySettings_ = other.safetySettings_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureSafetySettingsIsMutable();
            safetySettings_.addAll(other.safetySettings_);
          }
          onChanged();
        }
      } else {
        if (!other.safetySettings_.isEmpty()) {
          if (safetySettingsBuilder_.isEmpty()) {
            safetySettingsBuilder_.dispose();
            safetySettingsBuilder_ = null;
            safetySettings_ = other.safetySettings_;
            bitField0_ = (bitField0_ & ~0x00000080);
            safetySettingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSafetySettingsFieldBuilder() : null;
          } else {
            safetySettingsBuilder_.addAllMessages(other.safetySettings_);
          }
        }
      }
      if (!other.stopSequences_.isEmpty()) {
        if (stopSequences_.isEmpty()) {
          stopSequences_ = other.stopSequences_;
          bitField0_ |= 0x00000100;
        } else {
          ensureStopSequencesIsMutable();
          stopSequences_.addAll(other.stopSequences_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              model_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPromptFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 29: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              candidateCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              maxOutputTokens_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 53: {
              topP_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 56: {
              topK_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              com.google.ai.generativelanguage.v1beta3.SafetySetting m =
                  input.readMessage(
                      com.google.ai.generativelanguage.v1beta3.SafetySetting.parser(),
                      extensionRegistry);
              if (safetySettingsBuilder_ == null) {
                ensureSafetySettingsIsMutable();
                safetySettings_.add(m);
              } else {
                safetySettingsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStopSequencesIsMutable();
              stopSequences_.add(s);
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object model_ = "";
    /**
     * <pre>
     * Required. The name of the `Model` or `TunedModel` to use for generating the
     * completion.
     * Examples:
     *  models/text-bison-001
     *  tunedModels/sentence-translator-u3b7m
     * </pre>
     *
     * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The name of the `Model` or `TunedModel` to use for generating the
     * completion.
     * Examples:
     *  models/text-bison-001
     *  tunedModels/sentence-translator-u3b7m
     * </pre>
     *
     * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The name of the `Model` or `TunedModel` to use for generating the
     * completion.
     * Examples:
     *  models/text-bison-001
     *  tunedModels/sentence-translator-u3b7m
     * </pre>
     *
     * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      model_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The name of the `Model` or `TunedModel` to use for generating the
     * completion.
     * Examples:
     *  models/text-bison-001
     *  tunedModels/sentence-translator-u3b7m
     * </pre>
     *
     * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      model_ = getDefaultInstance().getModel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The name of the `Model` or `TunedModel` to use for generating the
     * completion.
     * Examples:
     *  models/text-bison-001
     *  tunedModels/sentence-translator-u3b7m
     * </pre>
     *
     * <code>string model = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      model_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.ai.generativelanguage.v1beta3.TextPrompt prompt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.TextPrompt, com.google.ai.generativelanguage.v1beta3.TextPrompt.Builder, com.google.ai.generativelanguage.v1beta3.TextPromptOrBuilder> promptBuilder_;
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the prompt field is set.
     */
    public boolean hasPrompt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The prompt.
     */
    public com.google.ai.generativelanguage.v1beta3.TextPrompt getPrompt() {
      if (promptBuilder_ == null) {
        return prompt_ == null ? com.google.ai.generativelanguage.v1beta3.TextPrompt.getDefaultInstance() : prompt_;
      } else {
        return promptBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPrompt(com.google.ai.generativelanguage.v1beta3.TextPrompt value) {
      if (promptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prompt_ = value;
      } else {
        promptBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPrompt(
        com.google.ai.generativelanguage.v1beta3.TextPrompt.Builder builderForValue) {
      if (promptBuilder_ == null) {
        prompt_ = builderForValue.build();
      } else {
        promptBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergePrompt(com.google.ai.generativelanguage.v1beta3.TextPrompt value) {
      if (promptBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          prompt_ != null &&
          prompt_ != com.google.ai.generativelanguage.v1beta3.TextPrompt.getDefaultInstance()) {
          getPromptBuilder().mergeFrom(value);
        } else {
          prompt_ = value;
        }
      } else {
        promptBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearPrompt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      prompt_ = null;
      if (promptBuilder_ != null) {
        promptBuilder_.dispose();
        promptBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextPrompt.Builder getPromptBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPromptFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.ai.generativelanguage.v1beta3.TextPromptOrBuilder getPromptOrBuilder() {
      if (promptBuilder_ != null) {
        return promptBuilder_.getMessageOrBuilder();
      } else {
        return prompt_ == null ?
            com.google.ai.generativelanguage.v1beta3.TextPrompt.getDefaultInstance() : prompt_;
      }
    }
    /**
     * <pre>
     * Required. The free-form input text given to the model as a prompt.
     *
     * Given a prompt, the model will generate a TextCompletion response it
     * predicts as the completion of the input text.
     * </pre>
     *
     * <code>.google.ai.generativelanguage.v1beta3.TextPrompt prompt = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.TextPrompt, com.google.ai.generativelanguage.v1beta3.TextPrompt.Builder, com.google.ai.generativelanguage.v1beta3.TextPromptOrBuilder> 
        getPromptFieldBuilder() {
      if (promptBuilder_ == null) {
        promptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.TextPrompt, com.google.ai.generativelanguage.v1beta3.TextPrompt.Builder, com.google.ai.generativelanguage.v1beta3.TextPromptOrBuilder>(
                getPrompt(),
                getParentForChildren(),
                isClean());
        prompt_ = null;
      }
      return promptBuilder_;
    }

    private float temperature_ ;
    /**
     * <pre>
     * Optional. Controls the randomness of the output.
     * Note: The default value varies by model, see the `Model.temperature`
     * attribute of the `Model` returned the `getModel` function.
     *
     * Values can range from [0.0,1.0],
     * inclusive. A value closer to 1.0 will produce responses that are more
     * varied and creative, while a value closer to 0.0 will typically result in
     * more straightforward responses from the model.
     * </pre>
     *
     * <code>optional float temperature = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the temperature field is set.
     */
    @java.lang.Override
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Optional. Controls the randomness of the output.
     * Note: The default value varies by model, see the `Model.temperature`
     * attribute of the `Model` returned the `getModel` function.
     *
     * Values can range from [0.0,1.0],
     * inclusive. A value closer to 1.0 will produce responses that are more
     * varied and creative, while a value closer to 0.0 will typically result in
     * more straightforward responses from the model.
     * </pre>
     *
     * <code>optional float temperature = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <pre>
     * Optional. Controls the randomness of the output.
     * Note: The default value varies by model, see the `Model.temperature`
     * attribute of the `Model` returned the `getModel` function.
     *
     * Values can range from [0.0,1.0],
     * inclusive. A value closer to 1.0 will produce responses that are more
     * varied and creative, while a value closer to 0.0 will typically result in
     * more straightforward responses from the model.
     * </pre>
     *
     * <code>optional float temperature = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {

      temperature_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Controls the randomness of the output.
     * Note: The default value varies by model, see the `Model.temperature`
     * attribute of the `Model` returned the `getModel` function.
     *
     * Values can range from [0.0,1.0],
     * inclusive. A value closer to 1.0 will produce responses that are more
     * varied and creative, while a value closer to 0.0 will typically result in
     * more straightforward responses from the model.
     * </pre>
     *
     * <code>optional float temperature = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000004);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private int candidateCount_ ;
    /**
     * <pre>
     * Optional. Number of generated responses to return.
     *
     * This value must be between [1, 8], inclusive. If unset, this will default
     * to 1.
     * </pre>
     *
     * <code>optional int32 candidate_count = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the candidateCount field is set.
     */
    @java.lang.Override
    public boolean hasCandidateCount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Optional. Number of generated responses to return.
     *
     * This value must be between [1, 8], inclusive. If unset, this will default
     * to 1.
     * </pre>
     *
     * <code>optional int32 candidate_count = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The candidateCount.
     */
    @java.lang.Override
    public int getCandidateCount() {
      return candidateCount_;
    }
    /**
     * <pre>
     * Optional. Number of generated responses to return.
     *
     * This value must be between [1, 8], inclusive. If unset, this will default
     * to 1.
     * </pre>
     *
     * <code>optional int32 candidate_count = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The candidateCount to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateCount(int value) {

      candidateCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Number of generated responses to return.
     *
     * This value must be between [1, 8], inclusive. If unset, this will default
     * to 1.
     * </pre>
     *
     * <code>optional int32 candidate_count = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      candidateCount_ = 0;
      onChanged();
      return this;
    }

    private int maxOutputTokens_ ;
    /**
     * <pre>
     * Optional. The maximum number of tokens to include in a candidate.
     *
     * If unset, this will default to output_token_limit specified in the `Model`
     * specification.
     * </pre>
     *
     * <code>optional int32 max_output_tokens = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the maxOutputTokens field is set.
     */
    @java.lang.Override
    public boolean hasMaxOutputTokens() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Optional. The maximum number of tokens to include in a candidate.
     *
     * If unset, this will default to output_token_limit specified in the `Model`
     * specification.
     * </pre>
     *
     * <code>optional int32 max_output_tokens = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The maxOutputTokens.
     */
    @java.lang.Override
    public int getMaxOutputTokens() {
      return maxOutputTokens_;
    }
    /**
     * <pre>
     * Optional. The maximum number of tokens to include in a candidate.
     *
     * If unset, this will default to output_token_limit specified in the `Model`
     * specification.
     * </pre>
     *
     * <code>optional int32 max_output_tokens = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The maxOutputTokens to set.
     * @return This builder for chaining.
     */
    public Builder setMaxOutputTokens(int value) {

      maxOutputTokens_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The maximum number of tokens to include in a candidate.
     *
     * If unset, this will default to output_token_limit specified in the `Model`
     * specification.
     * </pre>
     *
     * <code>optional int32 max_output_tokens = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxOutputTokens() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxOutputTokens_ = 0;
      onChanged();
      return this;
    }

    private float topP_ ;
    /**
     * <pre>
     * Optional. The maximum cumulative probability of tokens to consider when
     * sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Tokens are sorted based on their assigned probabilities so that only the
     * most likely tokens are considered. Top-k sampling directly limits the
     * maximum number of tokens to consider, while Nucleus sampling limits number
     * of tokens based on the cumulative probability.
     *
     * Note: The default value varies by model, see the `Model.top_p`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional float top_p = 6 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the topP field is set.
     */
    @java.lang.Override
    public boolean hasTopP() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Optional. The maximum cumulative probability of tokens to consider when
     * sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Tokens are sorted based on their assigned probabilities so that only the
     * most likely tokens are considered. Top-k sampling directly limits the
     * maximum number of tokens to consider, while Nucleus sampling limits number
     * of tokens based on the cumulative probability.
     *
     * Note: The default value varies by model, see the `Model.top_p`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional float top_p = 6 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The topP.
     */
    @java.lang.Override
    public float getTopP() {
      return topP_;
    }
    /**
     * <pre>
     * Optional. The maximum cumulative probability of tokens to consider when
     * sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Tokens are sorted based on their assigned probabilities so that only the
     * most likely tokens are considered. Top-k sampling directly limits the
     * maximum number of tokens to consider, while Nucleus sampling limits number
     * of tokens based on the cumulative probability.
     *
     * Note: The default value varies by model, see the `Model.top_p`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional float top_p = 6 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The topP to set.
     * @return This builder for chaining.
     */
    public Builder setTopP(float value) {

      topP_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The maximum cumulative probability of tokens to consider when
     * sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Tokens are sorted based on their assigned probabilities so that only the
     * most likely tokens are considered. Top-k sampling directly limits the
     * maximum number of tokens to consider, while Nucleus sampling limits number
     * of tokens based on the cumulative probability.
     *
     * Note: The default value varies by model, see the `Model.top_p`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional float top_p = 6 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearTopP() {
      bitField0_ = (bitField0_ & ~0x00000020);
      topP_ = 0F;
      onChanged();
      return this;
    }

    private int topK_ ;
    /**
     * <pre>
     * Optional. The maximum number of tokens to consider when sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * Defaults to 40.
     *
     * Note: The default value varies by model, see the `Model.top_k`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional int32 top_k = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return Whether the topK field is set.
     */
    @java.lang.Override
    public boolean hasTopK() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Optional. The maximum number of tokens to consider when sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * Defaults to 40.
     *
     * Note: The default value varies by model, see the `Model.top_k`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional int32 top_k = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return The topK.
     */
    @java.lang.Override
    public int getTopK() {
      return topK_;
    }
    /**
     * <pre>
     * Optional. The maximum number of tokens to consider when sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * Defaults to 40.
     *
     * Note: The default value varies by model, see the `Model.top_k`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional int32 top_k = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param value The topK to set.
     * @return This builder for chaining.
     */
    public Builder setTopK(int value) {

      topK_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The maximum number of tokens to consider when sampling.
     *
     * The model uses combined Top-k and nucleus sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * Defaults to 40.
     *
     * Note: The default value varies by model, see the `Model.top_k`
     * attribute of the `Model` returned the `getModel` function.
     * </pre>
     *
     * <code>optional int32 top_k = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return This builder for chaining.
     */
    public Builder clearTopK() {
      bitField0_ = (bitField0_ & ~0x00000040);
      topK_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.ai.generativelanguage.v1beta3.SafetySetting> safetySettings_ =
      java.util.Collections.emptyList();
    private void ensureSafetySettingsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        safetySettings_ = new java.util.ArrayList<com.google.ai.generativelanguage.v1beta3.SafetySetting>(safetySettings_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.SafetySetting, com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder, com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder> safetySettingsBuilder_;

    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetySetting> getSafetySettingsList() {
      if (safetySettingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(safetySettings_);
      } else {
        return safetySettingsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public int getSafetySettingsCount() {
      if (safetySettingsBuilder_ == null) {
        return safetySettings_.size();
      } else {
        return safetySettingsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetySetting getSafetySettings(int index) {
      if (safetySettingsBuilder_ == null) {
        return safetySettings_.get(index);
      } else {
        return safetySettingsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder setSafetySettings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetySetting value) {
      if (safetySettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetySettingsIsMutable();
        safetySettings_.set(index, value);
        onChanged();
      } else {
        safetySettingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder setSafetySettings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder builderForValue) {
      if (safetySettingsBuilder_ == null) {
        ensureSafetySettingsIsMutable();
        safetySettings_.set(index, builderForValue.build());
        onChanged();
      } else {
        safetySettingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder addSafetySettings(com.google.ai.generativelanguage.v1beta3.SafetySetting value) {
      if (safetySettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetySettingsIsMutable();
        safetySettings_.add(value);
        onChanged();
      } else {
        safetySettingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder addSafetySettings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetySetting value) {
      if (safetySettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetySettingsIsMutable();
        safetySettings_.add(index, value);
        onChanged();
      } else {
        safetySettingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder addSafetySettings(
        com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder builderForValue) {
      if (safetySettingsBuilder_ == null) {
        ensureSafetySettingsIsMutable();
        safetySettings_.add(builderForValue.build());
        onChanged();
      } else {
        safetySettingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder addSafetySettings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder builderForValue) {
      if (safetySettingsBuilder_ == null) {
        ensureSafetySettingsIsMutable();
        safetySettings_.add(index, builderForValue.build());
        onChanged();
      } else {
        safetySettingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder addAllSafetySettings(
        java.lang.Iterable<? extends com.google.ai.generativelanguage.v1beta3.SafetySetting> values) {
      if (safetySettingsBuilder_ == null) {
        ensureSafetySettingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, safetySettings_);
        onChanged();
      } else {
        safetySettingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder clearSafetySettings() {
      if (safetySettingsBuilder_ == null) {
        safetySettings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        safetySettingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public Builder removeSafetySettings(int index) {
      if (safetySettingsBuilder_ == null) {
        ensureSafetySettingsIsMutable();
        safetySettings_.remove(index);
        onChanged();
      } else {
        safetySettingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder getSafetySettingsBuilder(
        int index) {
      return getSafetySettingsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder getSafetySettingsOrBuilder(
        int index) {
      if (safetySettingsBuilder_ == null) {
        return safetySettings_.get(index);  } else {
        return safetySettingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder> 
         getSafetySettingsOrBuilderList() {
      if (safetySettingsBuilder_ != null) {
        return safetySettingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(safetySettings_);
      }
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder addSafetySettingsBuilder() {
      return getSafetySettingsFieldBuilder().addBuilder(
          com.google.ai.generativelanguage.v1beta3.SafetySetting.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder addSafetySettingsBuilder(
        int index) {
      return getSafetySettingsFieldBuilder().addBuilder(
          index, com.google.ai.generativelanguage.v1beta3.SafetySetting.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of unique `SafetySetting` instances for blocking unsafe content.
     *
     * that will be enforced on the `GenerateTextRequest.prompt` and
     * `GenerateTextResponse.candidates`. There should not be more than one
     * setting for each `SafetyCategory` type. The API will block any prompts and
     * responses that fail to meet the thresholds set by these settings. This list
     * overrides the default settings for each `SafetyCategory` specified in the
     * safety_settings. If there is no `SafetySetting` for a given
     * `SafetyCategory` provided in the list, the API will use the default safety
     * setting for that category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetySetting safety_settings = 8;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder> 
         getSafetySettingsBuilderList() {
      return getSafetySettingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.SafetySetting, com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder, com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder> 
        getSafetySettingsFieldBuilder() {
      if (safetySettingsBuilder_ == null) {
        safetySettingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.SafetySetting, com.google.ai.generativelanguage.v1beta3.SafetySetting.Builder, com.google.ai.generativelanguage.v1beta3.SafetySettingOrBuilder>(
                safetySettings_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        safetySettings_ = null;
      }
      return safetySettingsBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList stopSequences_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStopSequencesIsMutable() {
      if (!stopSequences_.isModifiable()) {
        stopSequences_ = new com.google.protobuf.LazyStringArrayList(stopSequences_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @return A list containing the stopSequences.
     */
    public com.google.protobuf.ProtocolStringList
        getStopSequencesList() {
      stopSequences_.makeImmutable();
      return stopSequences_;
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @return The count of stopSequences.
     */
    public int getStopSequencesCount() {
      return stopSequences_.size();
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @param index The index of the element to return.
     * @return The stopSequences at the given index.
     */
    public java.lang.String getStopSequences(int index) {
      return stopSequences_.get(index);
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stopSequences at the given index.
     */
    public com.google.protobuf.ByteString
        getStopSequencesBytes(int index) {
      return stopSequences_.getByteString(index);
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @param index The index to set the value at.
     * @param value The stopSequences to set.
     * @return This builder for chaining.
     */
    public Builder setStopSequences(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStopSequencesIsMutable();
      stopSequences_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @param value The stopSequences to add.
     * @return This builder for chaining.
     */
    public Builder addStopSequences(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStopSequencesIsMutable();
      stopSequences_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @param values The stopSequences to add.
     * @return This builder for chaining.
     */
    public Builder addAllStopSequences(
        java.lang.Iterable<java.lang.String> values) {
      ensureStopSequencesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stopSequences_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStopSequences() {
      stopSequences_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of character sequences (up to 5) that will stop output generation.
     * If specified, the API will stop at the first appearance of a stop
     * sequence. The stop sequence will not be included as part of the response.
     * </pre>
     *
     * <code>repeated string stop_sequences = 9;</code>
     * @param value The bytes of the stopSequences to add.
     * @return This builder for chaining.
     */
    public Builder addStopSequencesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStopSequencesIsMutable();
      stopSequences_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.ai.generativelanguage.v1beta3.GenerateTextRequest)
  }

  // @@protoc_insertion_point(class_scope:google.ai.generativelanguage.v1beta3.GenerateTextRequest)
  private static final com.google.ai.generativelanguage.v1beta3.GenerateTextRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ai.generativelanguage.v1beta3.GenerateTextRequest();
  }

  public static com.google.ai.generativelanguage.v1beta3.GenerateTextRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateTextRequest>
      PARSER = new com.google.protobuf.AbstractParser<GenerateTextRequest>() {
    @java.lang.Override
    public GenerateTextRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GenerateTextRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateTextRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.GenerateTextRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

