// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/model_service.proto

package com.google.ai.generativelanguage.v1beta3;

public final class ModelServiceProto {
  private ModelServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_GetModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_GetModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_ListModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_ListModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_GetTunedModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_GetTunedModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8google/ai/generativelanguage/v1beta3/m" +
      "odel_service.proto\022$google.ai.generative" +
      "language.v1beta3\0320google/ai/generativela" +
      "nguage/v1beta3/model.proto\0326google/ai/ge" +
      "nerativelanguage/v1beta3/tuned_model.pro" +
      "to\032\034google/api/annotations.proto\032\027google" +
      "/api/client.proto\032\037google/api/field_beha" +
      "vior.proto\032\031google/api/resource.proto\032#g" +
      "oogle/longrunning/operations.proto\032\033goog" +
      "le/protobuf/empty.proto\032 google/protobuf" +
      "/field_mask.proto\"Q\n\017GetModelRequest\022>\n\004" +
      "name\030\001 \001(\tB0\342A\001\002\372A)\n\'generativelanguage." +
      "googleapis.com/Model\":\n\021ListModelsReques" +
      "t\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t" +
      "\"j\n\022ListModelsResponse\022;\n\006models\030\001 \003(\0132+" +
      ".google.ai.generativelanguage.v1beta3.Mo" +
      "del\022\027\n\017next_page_token\030\002 \001(\t\"[\n\024GetTuned" +
      "ModelRequest\022C\n\004name\030\001 \001(\tB5\342A\001\002\372A.\n,gen" +
      "erativelanguage.googleapis.com/TunedMode" +
      "l\"K\n\026ListTunedModelsRequest\022\027\n\tpage_size" +
      "\030\001 \001(\005B\004\342A\001\001\022\030\n\npage_token\030\002 \001(\tB\004\342A\001\001\"z" +
      "\n\027ListTunedModelsResponse\022F\n\014tuned_model" +
      "s\030\001 \003(\01320.google.ai.generativelanguage.v" +
      "1beta3.TunedModel\022\027\n\017next_page_token\030\002 \001" +
      "(\t\"\234\001\n\027CreateTunedModelRequest\022!\n\016tuned_" +
      "model_id\030\001 \001(\tB\004\342A\001\001H\000\210\001\001\022K\n\013tuned_model" +
      "\030\002 \001(\01320.google.ai.generativelanguage.v1" +
      "beta3.TunedModelB\004\342A\001\002B\021\n\017_tuned_model_i" +
      "d\"\364\001\n\030CreateTunedModelMetadata\022F\n\013tuned_" +
      "model\030\005 \001(\tB1\372A.\n,generativelanguage.goo" +
      "gleapis.com/TunedModel\022\023\n\013total_steps\030\001 " +
      "\001(\005\022\027\n\017completed_steps\030\002 \001(\005\022\031\n\021complete" +
      "d_percent\030\003 \001(\002\022G\n\tsnapshots\030\004 \003(\01324.goo" +
      "gle.ai.generativelanguage.v1beta3.Tuning" +
      "Snapshot\"\235\001\n\027UpdateTunedModelRequest\022K\n\013" +
      "tuned_model\030\001 \001(\01320.google.ai.generative" +
      "language.v1beta3.TunedModelB\004\342A\001\002\0225\n\013upd" +
      "ate_mask\030\002 \001(\0132\032.google.protobuf.FieldMa" +
      "skB\004\342A\001\002\"^\n\027DeleteTunedModelRequest\022C\n\004n" +
      "ame\030\001 \001(\tB5\342A\001\002\372A.\n,generativelanguage.g" +
      "oogleapis.com/TunedModel2\340\n\n\014ModelServic" +
      "e\022\227\001\n\010GetModel\0225.google.ai.generativelan" +
      "guage.v1beta3.GetModelRequest\032+.google.a" +
      "i.generativelanguage.v1beta3.Model\"\'\332A\004n" +
      "ame\202\323\344\223\002\032\022\030/v1beta3/{name=models/*}\022\257\001\n\n" +
      "ListModels\0227.google.ai.generativelanguag" +
      "e.v1beta3.ListModelsRequest\0328.google.ai." +
      "generativelanguage.v1beta3.ListModelsRes" +
      "ponse\".\332A\024page_size,page_token\202\323\344\223\002\021\022\017/v" +
      "1beta3/models\022\253\001\n\rGetTunedModel\022:.google" +
      ".ai.generativelanguage.v1beta3.GetTunedM" +
      "odelRequest\0320.google.ai.generativelangua" +
      "ge.v1beta3.TunedModel\",\332A\004name\202\323\344\223\002\037\022\035/v" +
      "1beta3/{name=tunedModels/*}\022\303\001\n\017ListTune" +
      "dModels\022<.google.ai.generativelanguage.v" +
      "1beta3.ListTunedModelsRequest\032=.google.a" +
      "i.generativelanguage.v1beta3.ListTunedMo" +
      "delsResponse\"3\332A\024page_size,page_token\202\323\344" +
      "\223\002\026\022\024/v1beta3/tunedModels\022\357\001\n\020CreateTune" +
      "dModel\022=.google.ai.generativelanguage.v1" +
      "beta3.CreateTunedModelRequest\032\035.google.l" +
      "ongrunning.Operation\"}\312A&\n\nTunedModel\022\030C" +
      "reateTunedModelMetadata\332A\013tuned_model\332A\032" +
      "tuned_model_id,tuned_model\202\323\344\223\002#\"\024/v1bet" +
      "a3/tunedModels:\013tuned_model\022\335\001\n\020UpdateTu" +
      "nedModel\022=.google.ai.generativelanguage." +
      "v1beta3.UpdateTunedModelRequest\0320.google" +
      ".ai.generativelanguage.v1beta3.TunedMode" +
      "l\"X\332A\027tuned_model,update_mask\202\323\344\223\00282)/v1" +
      "beta3/{tuned_model.name=tunedModels/*}:\013" +
      "tuned_model\022\227\001\n\020DeleteTunedModel\022=.googl" +
      "e.ai.generativelanguage.v1beta3.DeleteTu" +
      "nedModelRequest\032\026.google.protobuf.Empty\"" +
      ",\332A\004name\202\323\344\223\002\037*\035/v1beta3/{name=tunedMode" +
      "ls/*}\032$\312A!generativelanguage.googleapis." +
      "comB\237\001\n(com.google.ai.generativelanguage" +
      ".v1beta3B\021ModelServiceProtoP\001Z^cloud.goo" +
      "gle.com/go/ai/generativelanguage/apiv1be" +
      "ta3/generativelanguagepb;generativelangu" +
      "agepbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ai.generativelanguage.v1beta3.ModelProto.getDescriptor(),
          com.google.ai.generativelanguage.v1beta3.TunedModelProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
        });
    internal_static_google_ai_generativelanguage_v1beta3_GetModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ai_generativelanguage_v1beta3_GetModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_GetModelRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_ai_generativelanguage_v1beta3_ListModelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ai_generativelanguage_v1beta3_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_ListModelsRequest_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", });
    internal_static_google_ai_generativelanguage_v1beta3_ListModelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ai_generativelanguage_v1beta3_ListModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_ListModelsResponse_descriptor,
        new java.lang.String[] { "Models", "NextPageToken", });
    internal_static_google_ai_generativelanguage_v1beta3_GetTunedModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_ai_generativelanguage_v1beta3_GetTunedModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_GetTunedModelRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsRequest_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", });
    internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_ListTunedModelsResponse_descriptor,
        new java.lang.String[] { "TunedModels", "NextPageToken", });
    internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelRequest_descriptor,
        new java.lang.String[] { "TunedModelId", "TunedModel", "TunedModelId", });
    internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_CreateTunedModelMetadata_descriptor,
        new java.lang.String[] { "TunedModel", "TotalSteps", "CompletedSteps", "CompletedPercent", "Snapshots", });
    internal_static_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_UpdateTunedModelRequest_descriptor,
        new java.lang.String[] { "TunedModel", "UpdateMask", });
    internal_static_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_DeleteTunedModelRequest_descriptor,
        new java.lang.String[] { "Name", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.ai.generativelanguage.v1beta3.ModelProto.getDescriptor();
    com.google.ai.generativelanguage.v1beta3.TunedModelProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
