// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/model.proto

package com.google.ai.generativelanguage.v1beta3;

/**
 * <pre>
 * Information about a Generative Language Model.
 * </pre>
 *
 * Protobuf type {@code google.ai.generativelanguage.v1beta3.Model}
 */
public final class Model extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.ai.generativelanguage.v1beta3.Model)
    ModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Model.newBuilder() to construct.
  private Model(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Model() {
    name_ = "";
    baseModelId_ = "";
    version_ = "";
    displayName_ = "";
    description_ = "";
    supportedGenerationMethods_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Model();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ai.generativelanguage.v1beta3.ModelProto.internal_static_google_ai_generativelanguage_v1beta3_Model_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ai.generativelanguage.v1beta3.ModelProto.internal_static_google_ai_generativelanguage_v1beta3_Model_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ai.generativelanguage.v1beta3.Model.class, com.google.ai.generativelanguage.v1beta3.Model.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Required. The resource name of the `Model`.
   *
   * Format: `models/{model}` with a `{model}` naming convention of:
   *
   * * "{base_model_id}-{version}"
   *
   * Examples:
   *
   * * `models/chat-bison-001`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The resource name of the `Model`.
   *
   * Format: `models/{model}` with a `{model}` naming convention of:
   *
   * * "{base_model_id}-{version}"
   *
   * Examples:
   *
   * * `models/chat-bison-001`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_MODEL_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object baseModelId_ = "";
  /**
   * <pre>
   * Required. The name of the base model, pass this to the generation request.
   *
   * Examples:
   *
   * * `chat-bison`
   * </pre>
   *
   * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The baseModelId.
   */
  @java.lang.Override
  public java.lang.String getBaseModelId() {
    java.lang.Object ref = baseModelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseModelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The name of the base model, pass this to the generation request.
   *
   * Examples:
   *
   * * `chat-bison`
   * </pre>
   *
   * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for baseModelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseModelIdBytes() {
    java.lang.Object ref = baseModelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseModelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <pre>
   * Required. The version number of the model.
   *
   * This represents the major version
   * </pre>
   *
   * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. The version number of the model.
   *
   * This represents the major version
   * </pre>
   *
   * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object displayName_ = "";
  /**
   * <pre>
   * The human-readable name of the model. E.g. "Chat Bison".
   *
   * The name can be up to 128 characters long and can consist of any UTF-8
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The human-readable name of the model. E.g. "Chat Bison".
   *
   * The name can be up to 128 characters long and can consist of any UTF-8
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * A short description of the model.
   * </pre>
   *
   * <code>string description = 5;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A short description of the model.
   * </pre>
   *
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_TOKEN_LIMIT_FIELD_NUMBER = 6;
  private int inputTokenLimit_ = 0;
  /**
   * <pre>
   * Maximum number of input tokens allowed for this model.
   * </pre>
   *
   * <code>int32 input_token_limit = 6;</code>
   * @return The inputTokenLimit.
   */
  @java.lang.Override
  public int getInputTokenLimit() {
    return inputTokenLimit_;
  }

  public static final int OUTPUT_TOKEN_LIMIT_FIELD_NUMBER = 7;
  private int outputTokenLimit_ = 0;
  /**
   * <pre>
   * Maximum number of output tokens available for this model.
   * </pre>
   *
   * <code>int32 output_token_limit = 7;</code>
   * @return The outputTokenLimit.
   */
  @java.lang.Override
  public int getOutputTokenLimit() {
    return outputTokenLimit_;
  }

  public static final int SUPPORTED_GENERATION_METHODS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList supportedGenerationMethods_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The model's supported generation methods.
   *
   * The method names are defined as Pascal case
   * strings, such as `generateMessage` which correspond to API methods.
   * </pre>
   *
   * <code>repeated string supported_generation_methods = 8;</code>
   * @return A list containing the supportedGenerationMethods.
   */
  public com.google.protobuf.ProtocolStringList
      getSupportedGenerationMethodsList() {
    return supportedGenerationMethods_;
  }
  /**
   * <pre>
   * The model's supported generation methods.
   *
   * The method names are defined as Pascal case
   * strings, such as `generateMessage` which correspond to API methods.
   * </pre>
   *
   * <code>repeated string supported_generation_methods = 8;</code>
   * @return The count of supportedGenerationMethods.
   */
  public int getSupportedGenerationMethodsCount() {
    return supportedGenerationMethods_.size();
  }
  /**
   * <pre>
   * The model's supported generation methods.
   *
   * The method names are defined as Pascal case
   * strings, such as `generateMessage` which correspond to API methods.
   * </pre>
   *
   * <code>repeated string supported_generation_methods = 8;</code>
   * @param index The index of the element to return.
   * @return The supportedGenerationMethods at the given index.
   */
  public java.lang.String getSupportedGenerationMethods(int index) {
    return supportedGenerationMethods_.get(index);
  }
  /**
   * <pre>
   * The model's supported generation methods.
   *
   * The method names are defined as Pascal case
   * strings, such as `generateMessage` which correspond to API methods.
   * </pre>
   *
   * <code>repeated string supported_generation_methods = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the supportedGenerationMethods at the given index.
   */
  public com.google.protobuf.ByteString
      getSupportedGenerationMethodsBytes(int index) {
    return supportedGenerationMethods_.getByteString(index);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 9;
  private float temperature_ = 0F;
  /**
   * <pre>
   * Controls the randomness of the output.
   *
   * Values can range over `[0.0,1.0]`, inclusive. A value closer to `1.0` will
   * produce responses that are more varied, while a value closer to `0.0` will
   * typically result in less surprising responses from the model.
   * This value specifies default to be used by the backend while making the
   * call to the model.
   * </pre>
   *
   * <code>optional float temperature = 9;</code>
   * @return Whether the temperature field is set.
   */
  @java.lang.Override
  public boolean hasTemperature() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Controls the randomness of the output.
   *
   * Values can range over `[0.0,1.0]`, inclusive. A value closer to `1.0` will
   * produce responses that are more varied, while a value closer to `0.0` will
   * typically result in less surprising responses from the model.
   * This value specifies default to be used by the backend while making the
   * call to the model.
   * </pre>
   *
   * <code>optional float temperature = 9;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int TOP_P_FIELD_NUMBER = 10;
  private float topP_ = 0F;
  /**
   * <pre>
   * For Nucleus sampling.
   *
   * Nucleus sampling considers the smallest set of tokens whose probability
   * sum is at least `top_p`.
   * This value specifies default to be used by the backend while making the
   * call to the model.
   * </pre>
   *
   * <code>optional float top_p = 10;</code>
   * @return Whether the topP field is set.
   */
  @java.lang.Override
  public boolean hasTopP() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * For Nucleus sampling.
   *
   * Nucleus sampling considers the smallest set of tokens whose probability
   * sum is at least `top_p`.
   * This value specifies default to be used by the backend while making the
   * call to the model.
   * </pre>
   *
   * <code>optional float top_p = 10;</code>
   * @return The topP.
   */
  @java.lang.Override
  public float getTopP() {
    return topP_;
  }

  public static final int TOP_K_FIELD_NUMBER = 11;
  private int topK_ = 0;
  /**
   * <pre>
   * For Top-k sampling.
   *
   * Top-k sampling considers the set of `top_k` most probable tokens.
   * This value specifies default to be used by the backend while making the
   * call to the model.
   * </pre>
   *
   * <code>optional int32 top_k = 11;</code>
   * @return Whether the topK field is set.
   */
  @java.lang.Override
  public boolean hasTopK() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * For Top-k sampling.
   *
   * Top-k sampling considers the set of `top_k` most probable tokens.
   * This value specifies default to be used by the backend while making the
   * call to the model.
   * </pre>
   *
   * <code>optional int32 top_k = 11;</code>
   * @return The topK.
   */
  @java.lang.Override
  public int getTopK() {
    return topK_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseModelId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, baseModelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(displayName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, displayName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    if (inputTokenLimit_ != 0) {
      output.writeInt32(6, inputTokenLimit_);
    }
    if (outputTokenLimit_ != 0) {
      output.writeInt32(7, outputTokenLimit_);
    }
    for (int i = 0; i < supportedGenerationMethods_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, supportedGenerationMethods_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeFloat(9, temperature_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeFloat(10, topP_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(11, topK_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseModelId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, baseModelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(displayName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, displayName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    if (inputTokenLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, inputTokenLimit_);
    }
    if (outputTokenLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, outputTokenLimit_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < supportedGenerationMethods_.size(); i++) {
        dataSize += computeStringSizeNoTag(supportedGenerationMethods_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSupportedGenerationMethodsList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(9, temperature_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, topP_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, topK_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ai.generativelanguage.v1beta3.Model)) {
      return super.equals(obj);
    }
    com.google.ai.generativelanguage.v1beta3.Model other = (com.google.ai.generativelanguage.v1beta3.Model) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getBaseModelId()
        .equals(other.getBaseModelId())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getDisplayName()
        .equals(other.getDisplayName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getInputTokenLimit()
        != other.getInputTokenLimit()) return false;
    if (getOutputTokenLimit()
        != other.getOutputTokenLimit()) return false;
    if (!getSupportedGenerationMethodsList()
        .equals(other.getSupportedGenerationMethodsList())) return false;
    if (hasTemperature() != other.hasTemperature()) return false;
    if (hasTemperature()) {
      if (java.lang.Float.floatToIntBits(getTemperature())
          != java.lang.Float.floatToIntBits(
              other.getTemperature())) return false;
    }
    if (hasTopP() != other.hasTopP()) return false;
    if (hasTopP()) {
      if (java.lang.Float.floatToIntBits(getTopP())
          != java.lang.Float.floatToIntBits(
              other.getTopP())) return false;
    }
    if (hasTopK() != other.hasTopK()) return false;
    if (hasTopK()) {
      if (getTopK()
          != other.getTopK()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BASE_MODEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBaseModelId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + DISPLAY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + INPUT_TOKEN_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getInputTokenLimit();
    hash = (37 * hash) + OUTPUT_TOKEN_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getOutputTokenLimit();
    if (getSupportedGenerationMethodsCount() > 0) {
      hash = (37 * hash) + SUPPORTED_GENERATION_METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getSupportedGenerationMethodsList().hashCode();
    }
    if (hasTemperature()) {
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
    }
    if (hasTopP()) {
      hash = (37 * hash) + TOP_P_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTopP());
    }
    if (hasTopK()) {
      hash = (37 * hash) + TOP_K_FIELD_NUMBER;
      hash = (53 * hash) + getTopK();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ai.generativelanguage.v1beta3.Model parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ai.generativelanguage.v1beta3.Model parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.Model parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ai.generativelanguage.v1beta3.Model prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Information about a Generative Language Model.
   * </pre>
   *
   * Protobuf type {@code google.ai.generativelanguage.v1beta3.Model}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.ai.generativelanguage.v1beta3.Model)
      com.google.ai.generativelanguage.v1beta3.ModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ai.generativelanguage.v1beta3.ModelProto.internal_static_google_ai_generativelanguage_v1beta3_Model_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ai.generativelanguage.v1beta3.ModelProto.internal_static_google_ai_generativelanguage_v1beta3_Model_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ai.generativelanguage.v1beta3.Model.class, com.google.ai.generativelanguage.v1beta3.Model.Builder.class);
    }

    // Construct using com.google.ai.generativelanguage.v1beta3.Model.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      baseModelId_ = "";
      version_ = "";
      displayName_ = "";
      description_ = "";
      inputTokenLimit_ = 0;
      outputTokenLimit_ = 0;
      supportedGenerationMethods_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      temperature_ = 0F;
      topP_ = 0F;
      topK_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ai.generativelanguage.v1beta3.ModelProto.internal_static_google_ai_generativelanguage_v1beta3_Model_descriptor;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.Model getDefaultInstanceForType() {
      return com.google.ai.generativelanguage.v1beta3.Model.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.Model build() {
      com.google.ai.generativelanguage.v1beta3.Model result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.Model buildPartial() {
      com.google.ai.generativelanguage.v1beta3.Model result = new com.google.ai.generativelanguage.v1beta3.Model(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.ai.generativelanguage.v1beta3.Model result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.baseModelId_ = baseModelId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.displayName_ = displayName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.inputTokenLimit_ = inputTokenLimit_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.outputTokenLimit_ = outputTokenLimit_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        supportedGenerationMethods_.makeImmutable();
        result.supportedGenerationMethods_ = supportedGenerationMethods_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.temperature_ = temperature_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.topP_ = topP_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.topK_ = topK_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ai.generativelanguage.v1beta3.Model) {
        return mergeFrom((com.google.ai.generativelanguage.v1beta3.Model)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ai.generativelanguage.v1beta3.Model other) {
      if (other == com.google.ai.generativelanguage.v1beta3.Model.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBaseModelId().isEmpty()) {
        baseModelId_ = other.baseModelId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getInputTokenLimit() != 0) {
        setInputTokenLimit(other.getInputTokenLimit());
      }
      if (other.getOutputTokenLimit() != 0) {
        setOutputTokenLimit(other.getOutputTokenLimit());
      }
      if (!other.supportedGenerationMethods_.isEmpty()) {
        if (supportedGenerationMethods_.isEmpty()) {
          supportedGenerationMethods_ = other.supportedGenerationMethods_;
          bitField0_ |= 0x00000080;
        } else {
          ensureSupportedGenerationMethodsIsMutable();
          supportedGenerationMethods_.addAll(other.supportedGenerationMethods_);
        }
        onChanged();
      }
      if (other.hasTemperature()) {
        setTemperature(other.getTemperature());
      }
      if (other.hasTopP()) {
        setTopP(other.getTopP());
      }
      if (other.hasTopK()) {
        setTopK(other.getTopK());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              baseModelId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              displayName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              inputTokenLimit_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              outputTokenLimit_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSupportedGenerationMethodsIsMutable();
              supportedGenerationMethods_.add(s);
              break;
            } // case 66
            case 77: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000100;
              break;
            } // case 77
            case 85: {
              topP_ = input.readFloat();
              bitField0_ |= 0x00000200;
              break;
            } // case 85
            case 88: {
              topK_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Required. The resource name of the `Model`.
     *
     * Format: `models/{model}` with a `{model}` naming convention of:
     *
     * * "{base_model_id}-{version}"
     *
     * Examples:
     *
     * * `models/chat-bison-001`
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The resource name of the `Model`.
     *
     * Format: `models/{model}` with a `{model}` naming convention of:
     *
     * * "{base_model_id}-{version}"
     *
     * Examples:
     *
     * * `models/chat-bison-001`
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The resource name of the `Model`.
     *
     * Format: `models/{model}` with a `{model}` naming convention of:
     *
     * * "{base_model_id}-{version}"
     *
     * Examples:
     *
     * * `models/chat-bison-001`
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The resource name of the `Model`.
     *
     * Format: `models/{model}` with a `{model}` naming convention of:
     *
     * * "{base_model_id}-{version}"
     *
     * Examples:
     *
     * * `models/chat-bison-001`
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The resource name of the `Model`.
     *
     * Format: `models/{model}` with a `{model}` naming convention of:
     *
     * * "{base_model_id}-{version}"
     *
     * Examples:
     *
     * * `models/chat-bison-001`
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object baseModelId_ = "";
    /**
     * <pre>
     * Required. The name of the base model, pass this to the generation request.
     *
     * Examples:
     *
     * * `chat-bison`
     * </pre>
     *
     * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The baseModelId.
     */
    public java.lang.String getBaseModelId() {
      java.lang.Object ref = baseModelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseModelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The name of the base model, pass this to the generation request.
     *
     * Examples:
     *
     * * `chat-bison`
     * </pre>
     *
     * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for baseModelId.
     */
    public com.google.protobuf.ByteString
        getBaseModelIdBytes() {
      java.lang.Object ref = baseModelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseModelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The name of the base model, pass this to the generation request.
     *
     * Examples:
     *
     * * `chat-bison`
     * </pre>
     *
     * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The baseModelId to set.
     * @return This builder for chaining.
     */
    public Builder setBaseModelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      baseModelId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The name of the base model, pass this to the generation request.
     *
     * Examples:
     *
     * * `chat-bison`
     * </pre>
     *
     * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseModelId() {
      baseModelId_ = getDefaultInstance().getBaseModelId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The name of the base model, pass this to the generation request.
     *
     * Examples:
     *
     * * `chat-bison`
     * </pre>
     *
     * <code>string base_model_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for baseModelId to set.
     * @return This builder for chaining.
     */
    public Builder setBaseModelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      baseModelId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     * Required. The version number of the model.
     *
     * This represents the major version
     * </pre>
     *
     * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. The version number of the model.
     *
     * This represents the major version
     * </pre>
     *
     * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. The version number of the model.
     *
     * This represents the major version
     * </pre>
     *
     * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The version number of the model.
     *
     * This represents the major version
     * </pre>
     *
     * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. The version number of the model.
     *
     * This represents the major version
     * </pre>
     *
     * <code>string version = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object displayName_ = "";
    /**
     * <pre>
     * The human-readable name of the model. E.g. "Chat Bison".
     *
     * The name can be up to 128 characters long and can consist of any UTF-8
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     * @return The displayName.
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The human-readable name of the model. E.g. "Chat Bison".
     *
     * The name can be up to 128 characters long and can consist of any UTF-8
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     * @return The bytes for displayName.
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The human-readable name of the model. E.g. "Chat Bison".
     *
     * The name can be up to 128 characters long and can consist of any UTF-8
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      displayName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The human-readable name of the model. E.g. "Chat Bison".
     *
     * The name can be up to 128 characters long and can consist of any UTF-8
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      displayName_ = getDefaultInstance().getDisplayName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The human-readable name of the model. E.g. "Chat Bison".
     *
     * The name can be up to 128 characters long and can consist of any UTF-8
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      displayName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * A short description of the model.
     * </pre>
     *
     * <code>string description = 5;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A short description of the model.
     * </pre>
     *
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A short description of the model.
     * </pre>
     *
     * <code>string description = 5;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A short description of the model.
     * </pre>
     *
     * <code>string description = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A short description of the model.
     * </pre>
     *
     * <code>string description = 5;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int inputTokenLimit_ ;
    /**
     * <pre>
     * Maximum number of input tokens allowed for this model.
     * </pre>
     *
     * <code>int32 input_token_limit = 6;</code>
     * @return The inputTokenLimit.
     */
    @java.lang.Override
    public int getInputTokenLimit() {
      return inputTokenLimit_;
    }
    /**
     * <pre>
     * Maximum number of input tokens allowed for this model.
     * </pre>
     *
     * <code>int32 input_token_limit = 6;</code>
     * @param value The inputTokenLimit to set.
     * @return This builder for chaining.
     */
    public Builder setInputTokenLimit(int value) {

      inputTokenLimit_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of input tokens allowed for this model.
     * </pre>
     *
     * <code>int32 input_token_limit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputTokenLimit() {
      bitField0_ = (bitField0_ & ~0x00000020);
      inputTokenLimit_ = 0;
      onChanged();
      return this;
    }

    private int outputTokenLimit_ ;
    /**
     * <pre>
     * Maximum number of output tokens available for this model.
     * </pre>
     *
     * <code>int32 output_token_limit = 7;</code>
     * @return The outputTokenLimit.
     */
    @java.lang.Override
    public int getOutputTokenLimit() {
      return outputTokenLimit_;
    }
    /**
     * <pre>
     * Maximum number of output tokens available for this model.
     * </pre>
     *
     * <code>int32 output_token_limit = 7;</code>
     * @param value The outputTokenLimit to set.
     * @return This builder for chaining.
     */
    public Builder setOutputTokenLimit(int value) {

      outputTokenLimit_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of output tokens available for this model.
     * </pre>
     *
     * <code>int32 output_token_limit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputTokenLimit() {
      bitField0_ = (bitField0_ & ~0x00000040);
      outputTokenLimit_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList supportedGenerationMethods_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSupportedGenerationMethodsIsMutable() {
      if (!supportedGenerationMethods_.isModifiable()) {
        supportedGenerationMethods_ = new com.google.protobuf.LazyStringArrayList(supportedGenerationMethods_);
      }
      bitField0_ |= 0x00000080;
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @return A list containing the supportedGenerationMethods.
     */
    public com.google.protobuf.ProtocolStringList
        getSupportedGenerationMethodsList() {
      supportedGenerationMethods_.makeImmutable();
      return supportedGenerationMethods_;
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @return The count of supportedGenerationMethods.
     */
    public int getSupportedGenerationMethodsCount() {
      return supportedGenerationMethods_.size();
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @param index The index of the element to return.
     * @return The supportedGenerationMethods at the given index.
     */
    public java.lang.String getSupportedGenerationMethods(int index) {
      return supportedGenerationMethods_.get(index);
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the supportedGenerationMethods at the given index.
     */
    public com.google.protobuf.ByteString
        getSupportedGenerationMethodsBytes(int index) {
      return supportedGenerationMethods_.getByteString(index);
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @param index The index to set the value at.
     * @param value The supportedGenerationMethods to set.
     * @return This builder for chaining.
     */
    public Builder setSupportedGenerationMethods(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSupportedGenerationMethodsIsMutable();
      supportedGenerationMethods_.set(index, value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @param value The supportedGenerationMethods to add.
     * @return This builder for chaining.
     */
    public Builder addSupportedGenerationMethods(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSupportedGenerationMethodsIsMutable();
      supportedGenerationMethods_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @param values The supportedGenerationMethods to add.
     * @return This builder for chaining.
     */
    public Builder addAllSupportedGenerationMethods(
        java.lang.Iterable<java.lang.String> values) {
      ensureSupportedGenerationMethodsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, supportedGenerationMethods_);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSupportedGenerationMethods() {
      supportedGenerationMethods_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The model's supported generation methods.
     *
     * The method names are defined as Pascal case
     * strings, such as `generateMessage` which correspond to API methods.
     * </pre>
     *
     * <code>repeated string supported_generation_methods = 8;</code>
     * @param value The bytes of the supportedGenerationMethods to add.
     * @return This builder for chaining.
     */
    public Builder addSupportedGenerationMethodsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSupportedGenerationMethodsIsMutable();
      supportedGenerationMethods_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private float temperature_ ;
    /**
     * <pre>
     * Controls the randomness of the output.
     *
     * Values can range over `[0.0,1.0]`, inclusive. A value closer to `1.0` will
     * produce responses that are more varied, while a value closer to `0.0` will
     * typically result in less surprising responses from the model.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float temperature = 9;</code>
     * @return Whether the temperature field is set.
     */
    @java.lang.Override
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * Controls the randomness of the output.
     *
     * Values can range over `[0.0,1.0]`, inclusive. A value closer to `1.0` will
     * produce responses that are more varied, while a value closer to `0.0` will
     * typically result in less surprising responses from the model.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float temperature = 9;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <pre>
     * Controls the randomness of the output.
     *
     * Values can range over `[0.0,1.0]`, inclusive. A value closer to `1.0` will
     * produce responses that are more varied, while a value closer to `0.0` will
     * typically result in less surprising responses from the model.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float temperature = 9;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {

      temperature_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Controls the randomness of the output.
     *
     * Values can range over `[0.0,1.0]`, inclusive. A value closer to `1.0` will
     * produce responses that are more varied, while a value closer to `0.0` will
     * typically result in less surprising responses from the model.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float temperature = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000100);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float topP_ ;
    /**
     * <pre>
     * For Nucleus sampling.
     *
     * Nucleus sampling considers the smallest set of tokens whose probability
     * sum is at least `top_p`.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float top_p = 10;</code>
     * @return Whether the topP field is set.
     */
    @java.lang.Override
    public boolean hasTopP() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * For Nucleus sampling.
     *
     * Nucleus sampling considers the smallest set of tokens whose probability
     * sum is at least `top_p`.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float top_p = 10;</code>
     * @return The topP.
     */
    @java.lang.Override
    public float getTopP() {
      return topP_;
    }
    /**
     * <pre>
     * For Nucleus sampling.
     *
     * Nucleus sampling considers the smallest set of tokens whose probability
     * sum is at least `top_p`.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float top_p = 10;</code>
     * @param value The topP to set.
     * @return This builder for chaining.
     */
    public Builder setTopP(float value) {

      topP_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For Nucleus sampling.
     *
     * Nucleus sampling considers the smallest set of tokens whose probability
     * sum is at least `top_p`.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional float top_p = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopP() {
      bitField0_ = (bitField0_ & ~0x00000200);
      topP_ = 0F;
      onChanged();
      return this;
    }

    private int topK_ ;
    /**
     * <pre>
     * For Top-k sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional int32 top_k = 11;</code>
     * @return Whether the topK field is set.
     */
    @java.lang.Override
    public boolean hasTopK() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * For Top-k sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional int32 top_k = 11;</code>
     * @return The topK.
     */
    @java.lang.Override
    public int getTopK() {
      return topK_;
    }
    /**
     * <pre>
     * For Top-k sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional int32 top_k = 11;</code>
     * @param value The topK to set.
     * @return This builder for chaining.
     */
    public Builder setTopK(int value) {

      topK_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For Top-k sampling.
     *
     * Top-k sampling considers the set of `top_k` most probable tokens.
     * This value specifies default to be used by the backend while making the
     * call to the model.
     * </pre>
     *
     * <code>optional int32 top_k = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopK() {
      bitField0_ = (bitField0_ & ~0x00000400);
      topK_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.ai.generativelanguage.v1beta3.Model)
  }

  // @@protoc_insertion_point(class_scope:google.ai.generativelanguage.v1beta3.Model)
  private static final com.google.ai.generativelanguage.v1beta3.Model DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ai.generativelanguage.v1beta3.Model();
  }

  public static com.google.ai.generativelanguage.v1beta3.Model getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Model>
      PARSER = new com.google.protobuf.AbstractParser<Model>() {
    @java.lang.Override
    public Model parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Model> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Model> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.Model getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

