// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/text_service.proto

package com.google.ai.generativelanguage.v1beta3;

/**
 * <pre>
 * Output text returned from a model.
 * </pre>
 *
 * Protobuf type {@code google.ai.generativelanguage.v1beta3.TextCompletion}
 */
public final class TextCompletion extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.ai.generativelanguage.v1beta3.TextCompletion)
    TextCompletionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TextCompletion.newBuilder() to construct.
  private TextCompletion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TextCompletion() {
    output_ = "";
    safetyRatings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TextCompletion();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_TextCompletion_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_TextCompletion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ai.generativelanguage.v1beta3.TextCompletion.class, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder.class);
  }

  private int bitField0_;
  public static final int OUTPUT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object output_ = "";
  /**
   * <pre>
   * Output only. The generated text returned from the model.
   * </pre>
   *
   * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The output.
   */
  @java.lang.Override
  public java.lang.String getOutput() {
    java.lang.Object ref = output_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      output_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Output only. The generated text returned from the model.
   * </pre>
   *
   * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for output.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputBytes() {
    java.lang.Object ref = output_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      output_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAFETY_RATINGS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyRating> safetyRatings_;
  /**
   * <pre>
   * Ratings for the safety of a response.
   *
   * There is at most one rating per category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyRating> getSafetyRatingsList() {
    return safetyRatings_;
  }
  /**
   * <pre>
   * Ratings for the safety of a response.
   *
   * There is at most one rating per category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder> 
      getSafetyRatingsOrBuilderList() {
    return safetyRatings_;
  }
  /**
   * <pre>
   * Ratings for the safety of a response.
   *
   * There is at most one rating per category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
   */
  @java.lang.Override
  public int getSafetyRatingsCount() {
    return safetyRatings_.size();
  }
  /**
   * <pre>
   * Ratings for the safety of a response.
   *
   * There is at most one rating per category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.SafetyRating getSafetyRatings(int index) {
    return safetyRatings_.get(index);
  }
  /**
   * <pre>
   * Ratings for the safety of a response.
   *
   * There is at most one rating per category.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder getSafetyRatingsOrBuilder(
      int index) {
    return safetyRatings_.get(index);
  }

  public static final int CITATION_METADATA_FIELD_NUMBER = 3;
  private com.google.ai.generativelanguage.v1beta3.CitationMetadata citationMetadata_;
  /**
   * <pre>
   * Output only. Citation information for model-generated `output` in this
   * `TextCompletion`.
   *
   * This field may be populated with attribution information for any text
   * included in the `output`.
   * </pre>
   *
   * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the citationMetadata field is set.
   */
  @java.lang.Override
  public boolean hasCitationMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Output only. Citation information for model-generated `output` in this
   * `TextCompletion`.
   *
   * This field may be populated with attribution information for any text
   * included in the `output`.
   * </pre>
   *
   * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The citationMetadata.
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.CitationMetadata getCitationMetadata() {
    return citationMetadata_ == null ? com.google.ai.generativelanguage.v1beta3.CitationMetadata.getDefaultInstance() : citationMetadata_;
  }
  /**
   * <pre>
   * Output only. Citation information for model-generated `output` in this
   * `TextCompletion`.
   *
   * This field may be populated with attribution information for any text
   * included in the `output`.
   * </pre>
   *
   * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.CitationMetadataOrBuilder getCitationMetadataOrBuilder() {
    return citationMetadata_ == null ? com.google.ai.generativelanguage.v1beta3.CitationMetadata.getDefaultInstance() : citationMetadata_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(output_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, output_);
    }
    for (int i = 0; i < safetyRatings_.size(); i++) {
      output.writeMessage(2, safetyRatings_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getCitationMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(output_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, output_);
    }
    for (int i = 0; i < safetyRatings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, safetyRatings_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCitationMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ai.generativelanguage.v1beta3.TextCompletion)) {
      return super.equals(obj);
    }
    com.google.ai.generativelanguage.v1beta3.TextCompletion other = (com.google.ai.generativelanguage.v1beta3.TextCompletion) obj;

    if (!getOutput()
        .equals(other.getOutput())) return false;
    if (!getSafetyRatingsList()
        .equals(other.getSafetyRatingsList())) return false;
    if (hasCitationMetadata() != other.hasCitationMetadata()) return false;
    if (hasCitationMetadata()) {
      if (!getCitationMetadata()
          .equals(other.getCitationMetadata())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
    hash = (53 * hash) + getOutput().hashCode();
    if (getSafetyRatingsCount() > 0) {
      hash = (37 * hash) + SAFETY_RATINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSafetyRatingsList().hashCode();
    }
    if (hasCitationMetadata()) {
      hash = (37 * hash) + CITATION_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getCitationMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ai.generativelanguage.v1beta3.TextCompletion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ai.generativelanguage.v1beta3.TextCompletion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Output text returned from a model.
   * </pre>
   *
   * Protobuf type {@code google.ai.generativelanguage.v1beta3.TextCompletion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.ai.generativelanguage.v1beta3.TextCompletion)
      com.google.ai.generativelanguage.v1beta3.TextCompletionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_TextCompletion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_TextCompletion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ai.generativelanguage.v1beta3.TextCompletion.class, com.google.ai.generativelanguage.v1beta3.TextCompletion.Builder.class);
    }

    // Construct using com.google.ai.generativelanguage.v1beta3.TextCompletion.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSafetyRatingsFieldBuilder();
        getCitationMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      output_ = "";
      if (safetyRatingsBuilder_ == null) {
        safetyRatings_ = java.util.Collections.emptyList();
      } else {
        safetyRatings_ = null;
        safetyRatingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      citationMetadata_ = null;
      if (citationMetadataBuilder_ != null) {
        citationMetadataBuilder_.dispose();
        citationMetadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ai.generativelanguage.v1beta3.TextServiceProto.internal_static_google_ai_generativelanguage_v1beta3_TextCompletion_descriptor;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.TextCompletion getDefaultInstanceForType() {
      return com.google.ai.generativelanguage.v1beta3.TextCompletion.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.TextCompletion build() {
      com.google.ai.generativelanguage.v1beta3.TextCompletion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ai.generativelanguage.v1beta3.TextCompletion buildPartial() {
      com.google.ai.generativelanguage.v1beta3.TextCompletion result = new com.google.ai.generativelanguage.v1beta3.TextCompletion(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.ai.generativelanguage.v1beta3.TextCompletion result) {
      if (safetyRatingsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          safetyRatings_ = java.util.Collections.unmodifiableList(safetyRatings_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.safetyRatings_ = safetyRatings_;
      } else {
        result.safetyRatings_ = safetyRatingsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.ai.generativelanguage.v1beta3.TextCompletion result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.output_ = output_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.citationMetadata_ = citationMetadataBuilder_ == null
            ? citationMetadata_
            : citationMetadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ai.generativelanguage.v1beta3.TextCompletion) {
        return mergeFrom((com.google.ai.generativelanguage.v1beta3.TextCompletion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ai.generativelanguage.v1beta3.TextCompletion other) {
      if (other == com.google.ai.generativelanguage.v1beta3.TextCompletion.getDefaultInstance()) return this;
      if (!other.getOutput().isEmpty()) {
        output_ = other.output_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (safetyRatingsBuilder_ == null) {
        if (!other.safetyRatings_.isEmpty()) {
          if (safetyRatings_.isEmpty()) {
            safetyRatings_ = other.safetyRatings_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSafetyRatingsIsMutable();
            safetyRatings_.addAll(other.safetyRatings_);
          }
          onChanged();
        }
      } else {
        if (!other.safetyRatings_.isEmpty()) {
          if (safetyRatingsBuilder_.isEmpty()) {
            safetyRatingsBuilder_.dispose();
            safetyRatingsBuilder_ = null;
            safetyRatings_ = other.safetyRatings_;
            bitField0_ = (bitField0_ & ~0x00000002);
            safetyRatingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSafetyRatingsFieldBuilder() : null;
          } else {
            safetyRatingsBuilder_.addAllMessages(other.safetyRatings_);
          }
        }
      }
      if (other.hasCitationMetadata()) {
        mergeCitationMetadata(other.getCitationMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              output_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.ai.generativelanguage.v1beta3.SafetyRating m =
                  input.readMessage(
                      com.google.ai.generativelanguage.v1beta3.SafetyRating.parser(),
                      extensionRegistry);
              if (safetyRatingsBuilder_ == null) {
                ensureSafetyRatingsIsMutable();
                safetyRatings_.add(m);
              } else {
                safetyRatingsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getCitationMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object output_ = "";
    /**
     * <pre>
     * Output only. The generated text returned from the model.
     * </pre>
     *
     * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The output.
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Output only. The generated text returned from the model.
     * </pre>
     *
     * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The bytes for output.
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Output only. The generated text returned from the model.
     * </pre>
     *
     * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The output to set.
     * @return This builder for chaining.
     */
    public Builder setOutput(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      output_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. The generated text returned from the model.
     * </pre>
     *
     * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutput() {
      output_ = getDefaultInstance().getOutput();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. The generated text returned from the model.
     * </pre>
     *
     * <code>string output = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The bytes for output to set.
     * @return This builder for chaining.
     */
    public Builder setOutputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      output_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyRating> safetyRatings_ =
      java.util.Collections.emptyList();
    private void ensureSafetyRatingsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        safetyRatings_ = new java.util.ArrayList<com.google.ai.generativelanguage.v1beta3.SafetyRating>(safetyRatings_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.SafetyRating, com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder, com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder> safetyRatingsBuilder_;

    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyRating> getSafetyRatingsList() {
      if (safetyRatingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(safetyRatings_);
      } else {
        return safetyRatingsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public int getSafetyRatingsCount() {
      if (safetyRatingsBuilder_ == null) {
        return safetyRatings_.size();
      } else {
        return safetyRatingsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyRating getSafetyRatings(int index) {
      if (safetyRatingsBuilder_ == null) {
        return safetyRatings_.get(index);
      } else {
        return safetyRatingsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder setSafetyRatings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyRating value) {
      if (safetyRatingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetyRatingsIsMutable();
        safetyRatings_.set(index, value);
        onChanged();
      } else {
        safetyRatingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder setSafetyRatings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder builderForValue) {
      if (safetyRatingsBuilder_ == null) {
        ensureSafetyRatingsIsMutable();
        safetyRatings_.set(index, builderForValue.build());
        onChanged();
      } else {
        safetyRatingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder addSafetyRatings(com.google.ai.generativelanguage.v1beta3.SafetyRating value) {
      if (safetyRatingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetyRatingsIsMutable();
        safetyRatings_.add(value);
        onChanged();
      } else {
        safetyRatingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder addSafetyRatings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyRating value) {
      if (safetyRatingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSafetyRatingsIsMutable();
        safetyRatings_.add(index, value);
        onChanged();
      } else {
        safetyRatingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder addSafetyRatings(
        com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder builderForValue) {
      if (safetyRatingsBuilder_ == null) {
        ensureSafetyRatingsIsMutable();
        safetyRatings_.add(builderForValue.build());
        onChanged();
      } else {
        safetyRatingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder addSafetyRatings(
        int index, com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder builderForValue) {
      if (safetyRatingsBuilder_ == null) {
        ensureSafetyRatingsIsMutable();
        safetyRatings_.add(index, builderForValue.build());
        onChanged();
      } else {
        safetyRatingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder addAllSafetyRatings(
        java.lang.Iterable<? extends com.google.ai.generativelanguage.v1beta3.SafetyRating> values) {
      if (safetyRatingsBuilder_ == null) {
        ensureSafetyRatingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, safetyRatings_);
        onChanged();
      } else {
        safetyRatingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder clearSafetyRatings() {
      if (safetyRatingsBuilder_ == null) {
        safetyRatings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        safetyRatingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public Builder removeSafetyRatings(int index) {
      if (safetyRatingsBuilder_ == null) {
        ensureSafetyRatingsIsMutable();
        safetyRatings_.remove(index);
        onChanged();
      } else {
        safetyRatingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder getSafetyRatingsBuilder(
        int index) {
      return getSafetyRatingsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder getSafetyRatingsOrBuilder(
        int index) {
      if (safetyRatingsBuilder_ == null) {
        return safetyRatings_.get(index);  } else {
        return safetyRatingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public java.util.List<? extends com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder> 
         getSafetyRatingsOrBuilderList() {
      if (safetyRatingsBuilder_ != null) {
        return safetyRatingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(safetyRatings_);
      }
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder addSafetyRatingsBuilder() {
      return getSafetyRatingsFieldBuilder().addBuilder(
          com.google.ai.generativelanguage.v1beta3.SafetyRating.getDefaultInstance());
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder addSafetyRatingsBuilder(
        int index) {
      return getSafetyRatingsFieldBuilder().addBuilder(
          index, com.google.ai.generativelanguage.v1beta3.SafetyRating.getDefaultInstance());
    }
    /**
     * <pre>
     * Ratings for the safety of a response.
     *
     * There is at most one rating per category.
     * </pre>
     *
     * <code>repeated .google.ai.generativelanguage.v1beta3.SafetyRating safety_ratings = 2;</code>
     */
    public java.util.List<com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder> 
         getSafetyRatingsBuilderList() {
      return getSafetyRatingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.SafetyRating, com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder, com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder> 
        getSafetyRatingsFieldBuilder() {
      if (safetyRatingsBuilder_ == null) {
        safetyRatingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.SafetyRating, com.google.ai.generativelanguage.v1beta3.SafetyRating.Builder, com.google.ai.generativelanguage.v1beta3.SafetyRatingOrBuilder>(
                safetyRatings_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        safetyRatings_ = null;
      }
      return safetyRatingsBuilder_;
    }

    private com.google.ai.generativelanguage.v1beta3.CitationMetadata citationMetadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.CitationMetadata, com.google.ai.generativelanguage.v1beta3.CitationMetadata.Builder, com.google.ai.generativelanguage.v1beta3.CitationMetadataOrBuilder> citationMetadataBuilder_;
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return Whether the citationMetadata field is set.
     */
    public boolean hasCitationMetadata() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The citationMetadata.
     */
    public com.google.ai.generativelanguage.v1beta3.CitationMetadata getCitationMetadata() {
      if (citationMetadataBuilder_ == null) {
        return citationMetadata_ == null ? com.google.ai.generativelanguage.v1beta3.CitationMetadata.getDefaultInstance() : citationMetadata_;
      } else {
        return citationMetadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder setCitationMetadata(com.google.ai.generativelanguage.v1beta3.CitationMetadata value) {
      if (citationMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        citationMetadata_ = value;
      } else {
        citationMetadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder setCitationMetadata(
        com.google.ai.generativelanguage.v1beta3.CitationMetadata.Builder builderForValue) {
      if (citationMetadataBuilder_ == null) {
        citationMetadata_ = builderForValue.build();
      } else {
        citationMetadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder mergeCitationMetadata(com.google.ai.generativelanguage.v1beta3.CitationMetadata value) {
      if (citationMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          citationMetadata_ != null &&
          citationMetadata_ != com.google.ai.generativelanguage.v1beta3.CitationMetadata.getDefaultInstance()) {
          getCitationMetadataBuilder().mergeFrom(value);
        } else {
          citationMetadata_ = value;
        }
      } else {
        citationMetadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder clearCitationMetadata() {
      bitField0_ = (bitField0_ & ~0x00000004);
      citationMetadata_ = null;
      if (citationMetadataBuilder_ != null) {
        citationMetadataBuilder_.dispose();
        citationMetadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public com.google.ai.generativelanguage.v1beta3.CitationMetadata.Builder getCitationMetadataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCitationMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public com.google.ai.generativelanguage.v1beta3.CitationMetadataOrBuilder getCitationMetadataOrBuilder() {
      if (citationMetadataBuilder_ != null) {
        return citationMetadataBuilder_.getMessageOrBuilder();
      } else {
        return citationMetadata_ == null ?
            com.google.ai.generativelanguage.v1beta3.CitationMetadata.getDefaultInstance() : citationMetadata_;
      }
    }
    /**
     * <pre>
     * Output only. Citation information for model-generated `output` in this
     * `TextCompletion`.
     *
     * This field may be populated with attribution information for any text
     * included in the `output`.
     * </pre>
     *
     * <code>optional .google.ai.generativelanguage.v1beta3.CitationMetadata citation_metadata = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.ai.generativelanguage.v1beta3.CitationMetadata, com.google.ai.generativelanguage.v1beta3.CitationMetadata.Builder, com.google.ai.generativelanguage.v1beta3.CitationMetadataOrBuilder> 
        getCitationMetadataFieldBuilder() {
      if (citationMetadataBuilder_ == null) {
        citationMetadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.ai.generativelanguage.v1beta3.CitationMetadata, com.google.ai.generativelanguage.v1beta3.CitationMetadata.Builder, com.google.ai.generativelanguage.v1beta3.CitationMetadataOrBuilder>(
                getCitationMetadata(),
                getParentForChildren(),
                isClean());
        citationMetadata_ = null;
      }
      return citationMetadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.ai.generativelanguage.v1beta3.TextCompletion)
  }

  // @@protoc_insertion_point(class_scope:google.ai.generativelanguage.v1beta3.TextCompletion)
  private static final com.google.ai.generativelanguage.v1beta3.TextCompletion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ai.generativelanguage.v1beta3.TextCompletion();
  }

  public static com.google.ai.generativelanguage.v1beta3.TextCompletion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TextCompletion>
      PARSER = new com.google.protobuf.AbstractParser<TextCompletion>() {
    @java.lang.Override
    public TextCompletion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TextCompletion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TextCompletion> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ai.generativelanguage.v1beta3.TextCompletion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

