// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/permission_service.proto

package com.google.ai.generativelanguage.v1beta3;

public interface TransferOwnershipResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ai.generativelanguage.v1beta3.TransferOwnershipResponse)
    com.google.protobuf.MessageOrBuilder {
}
