// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/tuned_model.proto

package com.google.ai.generativelanguage.v1beta3;

public final class TunedModelProto {
  private TunedModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_TunedModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_TunedModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_TunedModelSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_TunedModelSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_TuningTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_TuningTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_Hyperparameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_Hyperparameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_Dataset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_Dataset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_TuningExamples_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_TuningExamples_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_TuningExample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_TuningExample_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta3_TuningSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta3_TuningSnapshot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6google/ai/generativelanguage/v1beta3/t" +
      "uned_model.proto\022$google.ai.generativela" +
      "nguage.v1beta3\032\037google/api/field_behavio" +
      "r.proto\032\031google/api/resource.proto\032\037goog" +
      "le/protobuf/timestamp.proto\"\270\006\n\nTunedMod" +
      "el\022Z\n\022tuned_model_source\030\003 \001(\01326.google." +
      "ai.generativelanguage.v1beta3.TunedModel" +
      "SourceB\004\342A\001\001H\000\022F\n\nbase_model\030\004 \001(\tB0\342A\001\005" +
      "\372A)\n\'generativelanguage.googleapis.com/M" +
      "odelH\000\022\022\n\004name\030\001 \001(\tB\004\342A\001\003\022\032\n\014display_na" +
      "me\030\005 \001(\tB\004\342A\001\001\022\031\n\013description\030\006 \001(\tB\004\342A\001" +
      "\001\022\036\n\013temperature\030\013 \001(\002B\004\342A\001\001H\001\210\001\001\022\030\n\005top" +
      "_p\030\014 \001(\002B\004\342A\001\001H\002\210\001\001\022\030\n\005top_k\030\r \001(\005B\004\342A\001\001" +
      "H\003\210\001\001\022K\n\005state\030\007 \001(\01626.google.ai.generat" +
      "ivelanguage.v1beta3.TunedModel.StateB\004\342A" +
      "\001\003\0225\n\013create_time\030\010 \001(\0132\032.google.protobu" +
      "f.TimestampB\004\342A\001\003\0225\n\013update_time\030\t \001(\0132\032" +
      ".google.protobuf.TimestampB\004\342A\001\003\022K\n\013tuni" +
      "ng_task\030\n \001(\01320.google.ai.generativelang" +
      "uage.v1beta3.TuningTaskB\004\342A\001\002\"D\n\005State\022\025" +
      "\n\021STATE_UNSPECIFIED\020\000\022\014\n\010CREATING\020\001\022\n\n\006A" +
      "CTIVE\020\002\022\n\n\006FAILED\020\003:e\352Ab\n,generativelang" +
      "uage.googleapis.com/TunedModel\022\031tunedMod" +
      "els/{tuned_model}*\013tunedModels2\ntunedMod" +
      "elB\016\n\014source_modelB\016\n\014_temperatureB\010\n\006_t" +
      "op_pB\010\n\006_top_k\"\244\001\n\020TunedModelSource\022J\n\013t" +
      "uned_model\030\001 \001(\tB5\342A\001\005\372A.\n,generativelan" +
      "guage.googleapis.com/TunedModel\022D\n\nbase_" +
      "model\030\002 \001(\tB0\342A\001\003\372A)\n\'generativelanguage" +
      ".googleapis.com/Model\"\356\002\n\nTuningTask\0224\n\n" +
      "start_time\030\001 \001(\0132\032.google.protobuf.Times" +
      "tampB\004\342A\001\003\0227\n\rcomplete_time\030\002 \001(\0132\032.goog" +
      "le.protobuf.TimestampB\004\342A\001\003\022M\n\tsnapshots" +
      "\030\003 \003(\01324.google.ai.generativelanguage.v1" +
      "beta3.TuningSnapshotB\004\342A\001\003\022L\n\rtraining_d" +
      "ata\030\004 \001(\0132-.google.ai.generativelanguage" +
      ".v1beta3.DatasetB\006\342A\003\004\002\005\022T\n\017hyperparamet" +
      "ers\030\005 \001(\01325.google.ai.generativelanguage" +
      ".v1beta3.HyperparametersB\004\342A\001\005\"\243\001\n\017Hyper" +
      "parameters\022\036\n\013epoch_count\030\016 \001(\005B\004\342A\001\005H\000\210" +
      "\001\001\022\035\n\nbatch_size\030\017 \001(\005B\004\342A\001\005H\001\210\001\001\022 \n\rlea" +
      "rning_rate\030\020 \001(\002B\004\342A\001\005H\002\210\001\001B\016\n\014_epoch_co" +
      "untB\r\n\013_batch_sizeB\020\n\016_learning_rate\"d\n\007" +
      "Dataset\022N\n\010examples\030\001 \001(\01324.google.ai.ge" +
      "nerativelanguage.v1beta3.TuningExamplesB" +
      "\004\342A\001\001H\000B\t\n\007dataset\"]\n\016TuningExamples\022K\n\010" +
      "examples\030\001 \003(\01323.google.ai.generativelan" +
      "guage.v1beta3.TuningExampleB\004\342A\001\002\"P\n\rTun" +
      "ingExample\022\032\n\ntext_input\030\001 \001(\tB\004\342A\001\001H\000\022\024" +
      "\n\006output\030\003 \001(\tB\004\342A\001\002B\r\n\013model_input\"\212\001\n\016" +
      "TuningSnapshot\022\022\n\004step\030\001 \001(\005B\004\342A\001\003\022\023\n\005ep" +
      "och\030\002 \001(\005B\004\342A\001\003\022\027\n\tmean_loss\030\003 \001(\002B\004\342A\001\003" +
      "\0226\n\014compute_time\030\004 \001(\0132\032.google.protobuf" +
      ".TimestampB\004\342A\001\003B\235\001\n(com.google.ai.gener" +
      "ativelanguage.v1beta3B\017TunedModelProtoP\001" +
      "Z^cloud.google.com/go/ai/generativelangu" +
      "age/apiv1beta3/generativelanguagepb;gene" +
      "rativelanguagepbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_google_ai_generativelanguage_v1beta3_TunedModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ai_generativelanguage_v1beta3_TunedModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_TunedModel_descriptor,
        new java.lang.String[] { "TunedModelSource", "BaseModel", "Name", "DisplayName", "Description", "Temperature", "TopP", "TopK", "State", "CreateTime", "UpdateTime", "TuningTask", "SourceModel", "Temperature", "TopP", "TopK", });
    internal_static_google_ai_generativelanguage_v1beta3_TunedModelSource_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ai_generativelanguage_v1beta3_TunedModelSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_TunedModelSource_descriptor,
        new java.lang.String[] { "TunedModel", "BaseModel", });
    internal_static_google_ai_generativelanguage_v1beta3_TuningTask_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ai_generativelanguage_v1beta3_TuningTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_TuningTask_descriptor,
        new java.lang.String[] { "StartTime", "CompleteTime", "Snapshots", "TrainingData", "Hyperparameters", });
    internal_static_google_ai_generativelanguage_v1beta3_Hyperparameters_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_ai_generativelanguage_v1beta3_Hyperparameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_Hyperparameters_descriptor,
        new java.lang.String[] { "EpochCount", "BatchSize", "LearningRate", "EpochCount", "BatchSize", "LearningRate", });
    internal_static_google_ai_generativelanguage_v1beta3_Dataset_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_ai_generativelanguage_v1beta3_Dataset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_Dataset_descriptor,
        new java.lang.String[] { "Examples", "Dataset", });
    internal_static_google_ai_generativelanguage_v1beta3_TuningExamples_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_ai_generativelanguage_v1beta3_TuningExamples_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_TuningExamples_descriptor,
        new java.lang.String[] { "Examples", });
    internal_static_google_ai_generativelanguage_v1beta3_TuningExample_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_ai_generativelanguage_v1beta3_TuningExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_TuningExample_descriptor,
        new java.lang.String[] { "TextInput", "Output", "ModelInput", });
    internal_static_google_ai_generativelanguage_v1beta3_TuningSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_ai_generativelanguage_v1beta3_TuningSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta3_TuningSnapshot_descriptor,
        new java.lang.String[] { "Step", "Epoch", "MeanLoss", "ComputeTime", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
