// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta3/tuned_model.proto

package com.google.ai.generativelanguage.v1beta3;

public interface TunedModelSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ai.generativelanguage.v1beta3.TunedModelSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Immutable. The name of the `TunedModel` to use as the starting point for
   * training the new model.
   * Example: `tunedModels/my-tuned-model`
   * </pre>
   *
   * <code>string tuned_model = 1 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.resource_reference) = { ... }</code>
   * @return The tunedModel.
   */
  java.lang.String getTunedModel();
  /**
   * <pre>
   * Immutable. The name of the `TunedModel` to use as the starting point for
   * training the new model.
   * Example: `tunedModels/my-tuned-model`
   * </pre>
   *
   * <code>string tuned_model = 1 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for tunedModel.
   */
  com.google.protobuf.ByteString
      getTunedModelBytes();

  /**
   * <pre>
   * Output only. The name of the base `Model` this `TunedModel` was tuned from.
   * Example: `models/text-bison-001`
   * </pre>
   *
   * <code>string base_model = 2 [(.google.api.field_behavior) = OUTPUT_ONLY, (.google.api.resource_reference) = { ... }</code>
   * @return The baseModel.
   */
  java.lang.String getBaseModel();
  /**
   * <pre>
   * Output only. The name of the base `Model` this `TunedModel` was tuned from.
   * Example: `models/text-bison-001`
   * </pre>
   *
   * <code>string base_model = 2 [(.google.api.field_behavior) = OUTPUT_ONLY, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for baseModel.
   */
  com.google.protobuf.ByteString
      getBaseModelBytes();
}
